### ISSUE TITLE
Running tests throws ValueErrors for unknown Locales and subprocess errors

### ISSUE THREAD

**Issue by sudheesh001** [coala/coala#1279]
Here's a stacktrace

```
(coalaenv) [1:38:18] sudheeshsinganamalla:coala git:(master) $ ./run_tests.py
   1/118 | AlexBearTest
   2/118 | ApplyPatchActionTest
   3/118 | BearRunningTest
   4/118 | BearTest
   5/118 | BuildDbusServiceTest
   6/118 | BuildManPageTest
   7/118 | ClangASTPrintBearTest
   8/118 | ClangBearTest
   9/118 | ClangCloneDetectionBearTest
  10/118 | ClangCountingConditionsTest
  11/118 | ClangCountVectorCreatorTest
  12/118 | CliParsingTest
  13/118 | CloneDetectionRoutinesTest
  14/118 | coalaTest
  15/118 | CoffeeLintBearTest
  16/118 | CollectorsTest
  17/118 | ConfigurationGatheringTest
  18/118 | ConfParserTest
  19/118 | ConfWriterTest
  20/118 | ConsoleInteractionTest
  21/118 | ContextManagersTest
  22/118 | CorrectionBasedBearTest
  23/118 | CountVectorTest
  24/118 | CPPLintBearTest
  25/118 | CSharpLintBearTest
  26/118 | CSSLintBearTest
  27/118 | DbusAppTest
  28/118 | DbusDocumentTest
  29/118 | DbusServerTest
  30/118 | DbusTest
  31/118 | DecoratorsTest
  32/118 | DependenciesTest
  33/118 | DictUtilitiesTest
  34/118 | DiffTest
  35/118 | DockerfileLintBearTest
  36/118 | DocstyleDefinitionTest
  37/118 | DocumentationCommentTest
  38/118 | DocumentationCommentTest
  39/118 | DocumentationExtractionTest
  40/118 | EnumTest
  41/118 | EscapeTest
  42/118 | EspeakPrinterTest
  43/118 | ExceptionsTest
  44/118 | FunctionMetadataTest
  45/118 | GitCommitBearTest
  46/118 | GlobalBearTest
  47/118 | GlobbingTest
  48/118 | GofmtBearTest
  49/118 | GoVetBearTest
  50/118 | HiddenResultTest
  51/118 | HTMLWriterTest
  52/118 | ImportersTest
  53/118 | InBetweenMatchTest
  54/118 | IndentBearTest
  55/118 | InteractionsTest
  56/118 | JSHintBearTest
  57/118 | JSONEncoderTest
  58/118 | JSONFormatBearTest
  59/118 | KeywordBearTest
  60/118 | LanguageDefinitionTest
  61/118 | LanguageToolBearTest
test_invalid_files (bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest) ... ERROR
test_valid_files (bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest) ... /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:845: ResourceWarning: unclosed file <_io.TextIOWrapper name=10 encoding='UTF-8'>
  _cleanup()
/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:845: ResourceWarning: unclosed file <_io.TextIOWrapper name=8 encoding='UTF-8'>
  _cleanup()
/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:845: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='UTF-8'>
  _cleanup()
ERROR

======================================================================
ERROR: test_invalid_files (bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bears/tests/LocalBearTestHelper.py", line 294, in test_invalid_files
    self.assertLinesInvalid(self.uut, file, filename=filename)
  File "./bears/tests/LocalBearTestHelper.py", line 120, in assertLinesInvalid
    len(list(local_bear.execute(filename, lines))),
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: test_valid_files (bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bears/tests/LocalBearTestHelper.py", line 290, in test_valid_files
    self.assertLinesValid(self.uut, file, filename=filename)
  File "./bears/tests/LocalBearTestHelper.py", line 67, in assertLinesValid
    list(local_bear.execute(filename, lines)),
TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------
Ran 2 tests in 1.364s

FAILED (errors=2)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=13 encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=11 encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=9 encoding='UTF-8'>
######################################################################
  62/118 | LimitTest
  63/118 | LineCountBearTest
  64/118 | LineDiffTest
  65/118 | LineLengthBearTest
  66/118 | LineParserTest
  67/118 | LintTest
  68/118 | ListLogPrinterTest
  69/118 | LocalBearTest
  70/118 | LogMessageTest
  71/118 | LogPrinterTest
  72/118 | LogPrinterThreadTest
  73/118 | MakeTempTest
  74/118 | MarkdownBearTest
  75/118 | MatchTest
  76/118 | MatlabIndentationBearTest
  77/118 | NestedSearchInBetweenTest
  78/118 | OpenEditorActionTest
  79/118 | PEP8BearTest
  80/118 | PHPLintBearTest
  81/118 | PositionIsEscapedTest
  82/118 | PrintDebugMessageActionTest
  83/118 | ProcessingTest
  84/118 | ProseLintBearTest
  85/118 | PyCommentedCodeBearTest
  86/118 | PyImportSortBearTest
  87/118 | PyLintBearTest
  88/118 | PyUnusedCodeBearTest
  89/118 | reSTLintBearTest
Traceback (most recent call last):
  File "/Users/sudheeshsinganamalla/Documents/coala/bears/tests/natural_language/reSTLintBearTest.py", line 7, in <module>
    from bears.natural_language.reSTLintBear import reSTLintBear
  File "./bears/natural_language/reSTLintBear.py", line 1, in <module>
    from restructuredtext_lint import lint
  File "/Users/sudheeshsinganamalla/Documents/coalaenv/lib/python3.5/site-packages/restructuredtext_lint/__init__.py", line 3, in <module>
    from restructuredtext_lint.lint import lint, lint_file
  File "/Users/sudheeshsinganamalla/Documents/coalaenv/lib/python3.5/site-packages/restructuredtext_lint/lint.py", line 4, in <module>
    from docutils import utils
  File "/Users/sudheeshsinganamalla/Documents/coalaenv/lib/python3.5/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/Users/sudheeshsinganamalla/Documents/coalaenv/lib/python3.5/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Users/sudheeshsinganamalla/Documents/coalaenv/lib/python3.5/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/Users/sudheeshsinganamalla/Documents/coalaenv/lib/python3.5/locale.py", line 578, in getlocale
    return _parse_localename(localename)
  File "/Users/sudheeshsinganamalla/Documents/coalaenv/lib/python3.5/locale.py", line 487, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
######################################################################
  90/118 | RESULT_SEVERITYTest
  91/118 | ResultActionTest
  92/118 | ResultFilterTest
  93/118 | ResultTest
  94/118 | RubyLintBearTest
  95/118 | SearchForTest
  96/118 | SearchInBetweenTest
  97/118 | SectionCreatableTest
  98/118 | SectionFillingTest
  99/118 | SectionTest
 100/118 | SettingTest
 101/118 | ShellTest
 102/118 | ShowPatchActionTest
 103/118 | SourcePositionTest
 104/118 | SourceRangeTest
 105/118 | SpaceConsistencyBearTest
 106/118 | SpacingHelperTest
 107/118 | SplitTest
 108/118 | StringConverterTest
 109/118 | StringPrinterTest
 110/118 | TaggingTest
 111/118 | TextPositionTest
 112/118 | TextRangeTest
 113/118 | TrimEmptyMatchesTest
 114/118 | UnescapedSearchForTest
 115/118 | UnescapedSearchInBetweenTest
 116/118 | UnescapedSplitTest
 117/118 | UnescapedStripTest
 118/118 | UnescapeTest

Tests finished: failures in 2 of 118 test modules.
```

**Comment by sils1297** [comment]
On master

**Comment by sils1297** [comment]
?

**Comment by sudheesh001** [comment]
Looks like this is a mac specific problem, the easiest way to fix this is to export the `export LC_ALL=en_US.UTF-8`
But need to look into the other failing test.
```
(coalaenv) [1:40:19] sudheeshsinganamalla:coala git:(master) $ export LC_ALL=en_US.UTF-8
(coalaenv) [1:42:56] sudheeshsinganamalla:coala git:(master) $ ./run_tests.py
   1/118 | AlexBearTest
   2/118 | ApplyPatchActionTest
   3/118 | BearRunningTest
   4/118 | BearTest
   5/118 | BuildDbusServiceTest
   6/118 | BuildManPageTest
   7/118 | ClangASTPrintBearTest
   8/118 | ClangBearTest
   9/118 | ClangCloneDetectionBearTest
  10/118 | ClangCountingConditionsTest
  11/118 | ClangCountVectorCreatorTest
  12/118 | CliParsingTest
  13/118 | CloneDetectionRoutinesTest
  14/118 | coalaTest
  15/118 | CoffeeLintBearTest
  16/118 | CollectorsTest
  17/118 | ConfigurationGatheringTest
  18/118 | ConfParserTest
  19/118 | ConfWriterTest
  20/118 | ConsoleInteractionTest
  21/118 | ContextManagersTest
  22/118 | CorrectionBasedBearTest
  23/118 | CountVectorTest
  24/118 | CPPLintBearTest
  25/118 | CSharpLintBearTest
  26/118 | CSSLintBearTest
  27/118 | DbusAppTest
  28/118 | DbusDocumentTest
  29/118 | DbusServerTest
  30/118 | DbusTest
  31/118 | DecoratorsTest
  32/118 | DependenciesTest
  33/118 | DictUtilitiesTest
  34/118 | DiffTest
  35/118 | DockerfileLintBearTest
  36/118 | DocstyleDefinitionTest
  37/118 | DocumentationCommentTest
  38/118 | DocumentationCommentTest
  39/118 | DocumentationExtractionTest
  40/118 | EnumTest
  41/118 | EscapeTest
  42/118 | EspeakPrinterTest
  43/118 | ExceptionsTest
  44/118 | FunctionMetadataTest
  45/118 | GitCommitBearTest
  46/118 | GlobalBearTest
  47/118 | GlobbingTest
  48/118 | GofmtBearTest
  49/118 | GoVetBearTest
  50/118 | HiddenResultTest
  51/118 | HTMLWriterTest
  52/118 | ImportersTest
  53/118 | InBetweenMatchTest
  54/118 | IndentBearTest
  55/118 | InteractionsTest
  56/118 | JSHintBearTest
  57/118 | JSONEncoderTest
  58/118 | JSONFormatBearTest
  59/118 | KeywordBearTest
  60/118 | LanguageDefinitionTest
  61/118 | LanguageToolBearTest
test_invalid_files (bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest) ... ERROR
test_valid_files (bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest) ... /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:845: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='UTF-8'>
  _cleanup()
/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:845: ResourceWarning: unclosed file <_io.TextIOWrapper name=10 encoding='UTF-8'>
  _cleanup()
/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:845: ResourceWarning: unclosed file <_io.TextIOWrapper name=8 encoding='UTF-8'>
  _cleanup()
ERROR

======================================================================
ERROR: test_invalid_files (bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bears/tests/LocalBearTestHelper.py", line 294, in test_invalid_files
    self.assertLinesInvalid(self.uut, file, filename=filename)
  File "./bears/tests/LocalBearTestHelper.py", line 120, in assertLinesInvalid
    len(list(local_bear.execute(filename, lines))),
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: test_valid_files (bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bears/tests/LocalBearTestHelper.py", line 290, in test_valid_files
    self.assertLinesValid(self.uut, file, filename=filename)
  File "./bears/tests/LocalBearTestHelper.py", line 67, in assertLinesValid
    list(local_bear.execute(filename, lines)),
TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------
Ran 2 tests in 1.217s

FAILED (errors=2)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=9 encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=13 encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=11 encoding='UTF-8'>
######################################################################
  62/118 | LimitTest
  63/118 | LineCountBearTest
  64/118 | LineDiffTest
  65/118 | LineLengthBearTest
  66/118 | LineParserTest
  67/118 | LintTest
  68/118 | ListLogPrinterTest
  69/118 | LocalBearTest
  70/118 | LogMessageTest
  71/118 | LogPrinterTest
  72/118 | LogPrinterThreadTest
  73/118 | MakeTempTest
  74/118 | MarkdownBearTest
  75/118 | MatchTest
  76/118 | MatlabIndentationBearTest
  77/118 | NestedSearchInBetweenTest
  78/118 | OpenEditorActionTest
  79/118 | PEP8BearTest
  80/118 | PHPLintBearTest
  81/118 | PositionIsEscapedTest
  82/118 | PrintDebugMessageActionTest
  83/118 | ProcessingTest
  84/118 | ProseLintBearTest
  85/118 | PyCommentedCodeBearTest
  86/118 | PyImportSortBearTest
  87/118 | PyLintBearTest
  88/118 | PyUnusedCodeBearTest
  89/118 | reSTLintBearTest
  90/118 | RESULT_SEVERITYTest
  91/118 | ResultActionTest
  92/118 | ResultFilterTest
  93/118 | ResultTest
  94/118 | RubyLintBearTest
  95/118 | SearchForTest
  96/118 | SearchInBetweenTest
  97/118 | SectionCreatableTest
  98/118 | SectionFillingTest
  99/118 | SectionTest
 100/118 | SettingTest
 101/118 | ShellTest
 102/118 | ShowPatchActionTest
 103/118 | SourcePositionTest
 104/118 | SourceRangeTest
 105/118 | SpaceConsistencyBearTest
 106/118 | SpacingHelperTest
 107/118 | SplitTest
 108/118 | StringConverterTest
 109/118 | StringPrinterTest
 110/118 | TaggingTest
 111/118 | TextPositionTest
 112/118 | TextRangeTest
 113/118 | TrimEmptyMatchesTest
 114/118 | UnescapedSearchForTest
 115/118 | UnescapedSearchInBetweenTest
 116/118 | UnescapedSplitTest
 117/118 | UnescapedStripTest
 118/118 | UnescapeTest

Tests finished: failures in 1 of 118 test modules.
```

**Comment by sils1297** [comment]
Assigning @Udayan12167 for mac related problems :P

**Comment by sudheesh001** [comment]
https://gist.github.com/sudheesh001/fb9167effe66f97f1a45

**Comment by sudheesh001** [comment]
@sils1297 @Udayan12167 I am surprised that it works normally when running in the shell
```py
>>> import sys
>>> import unittest
>>>
>>> sys.path.insert(0, ".")
>>> from bears.tests.LocalBearTestHelper import verify_local_bear
>>> from bears.natural_language.LanguageToolBear import LanguageToolBear
>>>
>>> LanguageToolBearTest = verify_local_bear(
...     LanguageToolBear,
...     valid_files=(["A correct English sentence sounds nice in everyone's "
...                   "ears."], ),
...     invalid_files=(["  "],
...                    ["asdgaasdfgahsadf"],
...                    ['"quoted"']),
...     settings={'use_spaces': 'true'})
>>> LanguageToolBearTest
<class 'bears.tests.LocalBearTestHelper.verify_local_bear.<locals>.LocalBearTest'>
```
but fails when running it as `./run_tests.py` Needs a deeper check

**Comment by sils1297** [comment]
Well you don't seem to run the unit test main in your shell session so the
assertion is never executed

**Comment by jayvdb** [comment]
`run_tests.py ` was removed in a7bca64f2a , and we've also solved some locale problems recently with https://github.com/coala/coala/issues/3906 , so unlikely to be anything left to do here.
