### ISSUE TITLE
Unable to collect GitCommitBear - nltk importing html.entities

### ISSUE THREAD

**Issue by sils** [coala/coala#2053]
```
[WARNING][11:19:33] Unable to collect bears from /home/lasse/prog/coala-bears/bears/vcs/git/GitCommitBear.py. Probably the file is malformed or the module code raises an exception.
[DEBUG][11:19:33] Exception was:
Traceback (most recent call last):

  File "/home/lasse/prog/coala/coalib/collecting/Collectors.py", line 121, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/home/lasse/prog/coala/coalib/collecting/Collectors.py", line 23, in _import_bears
    types=list):

  File "/home/lasse/prog/coala/coalib/collecting/Importers.py", line 116, in iimport_objects
    attributes, local):

  File "/home/lasse/prog/coala/coalib/misc/Decorators.py", line 14, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/home/lasse/prog/coala/coalib/collecting/Importers.py", line 87, in _iimport_objects
    module = _import_module(file_path)

  File "/home/lasse/prog/coala/coalib/collecting/Importers.py", line 30, in _import_module
    return __import__(module_name)

  File "/home/lasse/prog/coala-bears/bears/vcs/git/GitCommitBear.py", line 1, in <module>
    import nltk

  File "/usr/lib/python3.5/site-packages/nltk-3.1-py3.5.egg/nltk/__init__.py", line 89, in <module>
    from nltk.internals import config_java

  File "/usr/lib/python3.5/site-packages/nltk-3.1-py3.5.egg/nltk/internals.py", line 29, in <module>
    from nltk import compat

  File "/usr/lib/python3.5/site-packages/nltk-3.1-py3.5.egg/nltk/compat.py", line 48, in <module>
    import html.entities as htmlentitydefs

ImportError: No module named 'html.entities'
```

**Comment by AbdealiJK** [comment]
Seems to be a system dependent problem.
But if you use pip to reinstall, it works out - http://stackoverflow.com/questions/20544694/importerror-no-module-named-html-entities

What system is this ? Does importing `nltk` in shell work ?

**Comment by AbdealiJK** [comment]
Wow, so apparently this is part of python (builtin)

```
>>> html.entities.__file__
'/home/ajk/.pyenv/versions/3.5.1/lib/python3.5/html/entities.py'
```
So, I think your python was compiled differently or your python2 and python3 are getting themselves confused ?

**Comment by AbdealiJK** [comment]
I seem to be getting the same thing !
No idea why. I can import html.entities in python shell, but the import of nltk works fine in shell.
```
Python 3.5.1 (default, Feb 11 2016, 08:32:46) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> import html.entities
>>>
```
CC @tushar-rishav as he made this part ?

**Comment by AbdealiJK** [comment]
On further analysis: 
coala -A says that html.entities not found:
```
<this is a truncated log>
$ coala -A -L DEBUG
[WARNING][09:08:36] Unable to collect bears from /home/ajk/Documents/coala/coala-bears/bears/vcs/git/GitCommitBear.py. Probably the file is malformed or the module code raises an exception.
[DEBUG][09:08:36] Exception was:
Traceback (most recent call last):
  File "/home/ajk/Documents/coala/coala/coalib/collecting/Collectors.py", line 121, in icollect_bears
    for bear in _import_bears(matching_file, kinds):
  File "/home/ajk/Documents/coala/coala/coalib/collecting/Collectors.py", line 23, in _import_bears
    types=list):
  File "/home/ajk/Documents/coala/coala/coalib/collecting/Importers.py", line 151, in iimport_objects
    attributes, local):
  File "/home/ajk/Documents/coala/coala/coalib/misc/Decorators.py", line 14, in yield_once_generator
    for item in iterator(*args, **kwargs):
  File "/home/ajk/Documents/coala/coala/coalib/collecting/Importers.py", line 122, in _iimport_objects
    module = _import_module(file_path)
  File "/home/ajk/Documents/coala/coala/coalib/collecting/Importers.py", line 30, in _import_module
    return __import__(module_name)
  File "/home/ajk/Documents/coala/coala-bears/bears/vcs/git/GitCommitBear.py", line 1, in <module>
    import nltk
  File "/home/ajk/.pyenv/versions/3.5.1/lib/python3.5/site-packages/nltk/__init__.py", line 89, in <module>
    from nltk.internals import config_java
  File "/home/ajk/.pyenv/versions/3.5.1/lib/python3.5/site-packages/nltk/internals.py", line 29, in <module>
    from nltk import compat
  File "/home/ajk/.pyenv/versions/3.5.1/lib/python3.5/site-packages/nltk/compat.py", line 48, in <module>
    import html.entities as htmlentitydefs
ImportError: No module named 'html.entities'
```
but coala says:
```
$ coala
Executing section Default...
Executing section python...
Executing section autopep8...
Executing section linelength...
Executing section DOCS...
Executing section commit...
[ERROR][09:09:46] NLTK data missing, install by running following commands `python -m nltk.downloader punkt maxent_treebank_pos_tagger averaged_perceptron_tagger`
```
Which means it was able to import `nltk` successfully in `coala` but not with `-A`. Interesting and weird.

**Comment by tushar-rishav** [comment]
This is so bizarre.

**Comment by Makman2** [comment]
had this error also somewhen, confirmed^^

**Comment by AbdealiJK** [comment]
So it seems this was caused because `bears.html` is clashing with builtin `html`.

So, no bear from `bears.html` can be run simultaneously with `GitCommitBear` for that reason. hence it failed only in `coala -A`

**Comment by AbdealiJK** [comment]
Also, this issue should have been in `coala-bear`

**Comment by Udayan12167** [comment]
```
[WARNING][17:36:38] Unable to collect bears from /usr/local/lib/python3.5/site-packages/coala_bears-0.10.0.dev99999999999999-py3.5.egg/bears/vcs/git/GitCommitBear.py. Probably the file is malformed or the module code raises an exception.
[INFO][17:36:38] Exception was:
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Collectors.py", line 125, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/usr/local/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Collectors.py", line 27, in _import_bears
    types=list):

  File "/usr/local/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)

  File "/usr/local/lib/python3.5/site-packages/coala_utils-0.5.1-py3.5.egg/coala_utils/decorators.py", line 24, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/usr/local/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)

  File "/usr/local/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)

  File "/usr/local/lib/python3.5/site-packages/coala_bears-0.10.0.dev99999999999999-py3.5.egg/bears/vcs/git/GitCommitBear.py", line 1, in <module>
    import nltk

  File "/usr/local/lib/python3.5/site-packages/nltk-3.2.1-py3.5.egg/nltk/__init__.py", line 89, in <module>
    from nltk.internals import config_java

  File "/usr/local/lib/python3.5/site-packages/nltk-3.2.1-py3.5.egg/nltk/internals.py", line 29, in <module>
    from nltk import compat

  File "/usr/local/lib/python3.5/site-packages/nltk-3.2.1-py3.5.egg/nltk/compat.py", line 50, in <module>
    import html.entities as htmlentitydefs

ImportError: No module named 'html.entities'
```

**Comment by sils** [comment]
Can we do somethign to prevent those kind of issues from reoccuring?

**Comment by sils** [comment]
@Udayan12167 is this reproducable with coala 0.9 or development?

**Comment by KVGarg** [comment]
How can we reproduce this error? I would like to give it a try!
