### ISSUE TITLE
Documentation parser breaks when malformed `:param` string is passed

### ISSUE THREAD

**Issue by arafsheikh** [coala/coala#2143]
When `:param some_parameter` is used instead of `:param some_parameter:` the following error is received.

``` text
[WARNING][20:43:05] The default coafile '.coafile' was not found. Ignoring it.
[ERROR][20:43:05] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[DEBUG][20:43:05] Exception was:
Traceback (most recent call last):

  File "/usr/local/lib/python3.4/dist-packages/coalib/coala_main.py", line 62, in run_coala
    autoapply=autoapply)

  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/ConfigurationGathering.py", line 310, in gather_configuration
    log_printer)

  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/SectionFilling.py", line 38, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/SectionFilling.py", line 74, in fill_section
    needed = bear.get_non_optional_settings()

  File "/usr/local/lib/python3.4/dist-packages/coalib/bears/Bear.py", line 196, in get_non_optional_settings
    return cls.get_metadata().non_optional_params

  File "/usr/local/lib/python3.4/dist-packages/coalib/bearlib/abstractions/Linter.py", line 228, in get_metadata
    cls._get_create_arguments_metadata())

  File "/usr/local/lib/python3.4/dist-packages/coalib/bearlib/abstractions/Linter.py", line 200, in _get_create_arguments_metadata
    omit={"filename", "file", "config_file"})

  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/FunctionMetadata.py", line 148, in from_function
    doc_comment = DocumentationComment.from_docstring(doc)

  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/DocumentationComment.py", line 48, in from_docstring
    param_dict[cur_param] = splitted[1].strip()

IndexError: list index out of range
```

**Comment by sils1297** [comment]
Needs proper error handling with a nice message

**Comment by NiklasMM** [comment]
Since `:param some_parameter` is clearly a malformed docstring it's ok to just yield a Result in this case.
