### ISSUE TITLE
PerlCriticBear, PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by maciejs** [coala/coala#2911]
### Overview Description

Running PerlCriticBear, error is displayed 

# Steps to Reproduce

1. "c:\Program Files\Python35\Scripts\coala.exe" --files test.pl --bears=PerlCriticBear

# Actual Results
[WARNING][17:31:31] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.
Executing section Default...
[ERROR][17:31:31] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:

d:\>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python35\lib\multiprocessing\spawn.py", line 100, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "c:\program files\python35\lib\multiprocessing\reduction.py", line 86, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied

# Expected Results

Report

# Reproducibility

Always, also when running as Administrator

# Additional Information:

Microsoft Windows [Version 6.1.7601]
Symantec Endpoint Protection 12.1.6 (not sure if it impacts, can't disable it)
Python 3.5.2
coala (0.8.1)
coala-bears (0.8.4)
coala-utils (0.4.10)

**Comment by sils** [comment]
What happened here, nobody triaged this for ten days? Let's see...

**Comment by sils** [comment]
This looks nasty. CC @Makman2 can you reproduce that?

**Comment by Makman2** [comment]
trying out the next days^^
