### ISSUE TITLE
Cannot install coala on Ubuntu

### ISSUE THREAD

**Issue by amelzer** [coala/coala#2917]
### I was trying to install coala on Ubuntu and failed

# Steps to Reproduce

1. While on `14.04.1-Ubuntu` using  `Python 3.4.3`, `pip 1.5.4 (python 3.4)` run `pip3 install coala`

# Actual Results
Coala installation fails with:

    Downloading/unpacking coala
    Downloading coala-0.8.1-py3-none-any.whl (169kB): 169kB downloaded
    Cleaning up...

    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2482, in _dep_map
        return self.__dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
        raise AttributeError(attr)
        AttributeError: _DistInfoDistribution__dep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
        req_to_install.extras):
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2291, in requires
        dm = self._dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2484, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
        parsed = next(parse_requirements(distvers))
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
        line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2583, in scan_list
        "Expected ',' or end-of-list in",line,"at",line[p:]
    ValueError: ("Expected ',' or end-of-list in", 'PyPrint >=0.2.5,==0.2.*', 'at', '*')

    Storing debug log for failure in /home/amelzer/.pip/pip.log

# Expected Results
Coala is installed 

# Additional Information:
Ubuntu Version:   `14.04.1-Ubuntu`
Python Version: `Python 3.4.3`
Pip Version: `pip 1.5.4 (python 3.4)`
Does also not work when trying to install with `sudo`

**Comment by amelzer** [comment]
Upgrading to `pip 8.1.2` solved the issue.

Are the minimum requirements for Python and Pip already documented somewhere? If not, it may be a way to improve the docs. :)

**Comment by sils** [comment]
Hey, we have this listed in the FAQ at least somewhere and it's a well known issue (as it affects all debian people), would you mind putting the info in the documentation at places where you'd expect them?

**Comment by sils** [comment]
This issue was moved to coala/documentation#237
