### ISSUE TITLE
WinError 87

### ISSUE THREAD

**Issue by Gregoor** [coala/coala#2991]
```
C:\code> coala --files=**\*.js --bears=ESLintBear
[WARNING][18:37:56] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.
Executing section Default...
[ERROR][18:37:57] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\gregor\appdata\local\programs\python\python35\lib\multiprocessing\spawn.py", line 100, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "c:\users\gregor\appdata\local\programs\python\python35\lib\multiprocessing\reduction.py", line 81, in steal_handle

    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```
Seem to be happening in every directory for me right now, any other infos I can give?

**Comment by tulphoon** [comment]
What's your Windows, Python and coala version?

**Comment by sils** [comment]
CC @Makman2 this shouldn't happen

**Comment by Makman2** [comment]
yeah @Gregoor please tell us your environment^^

**Comment by Gregoor** [comment]
Oh yeah right, should have thought of that. Win10 and python 3.5. I'll check the minor version later

**Comment by jayvdb** [comment]
@Gregoor, is this still happening for you?
We should have actioned this much sooner.  Apologies.
