### ISSUE TITLE
coala-ci 0.9 is not compatible with coala 0.8 .coafile

### ISSUE THREAD

**Issue by chauffer** [coala/coala#3128]
Error:
```$ coala-ci
WARNING:root:Use of `coala-ci` binary is deprecated, use `coala --non-interactive` instead.
[ERROR][12:25:35] During execution, we found that some required settings were not provided. They are:
language (from AnnotationBear) -  The programming language of the source code.
[ERROR][12:25:35] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][12:25:35] Exception was:
Traceback (most recent call last):

  File "/coala/coalib/coala_main.py", line 74, in run_coala
    arg_list=arg_list)

  File "/coala/coalib/settings/ConfigurationGathering.py", line 362, in gather_configuration
    log_printer)

  File "/coala/coalib/settings/SectionFilling.py", line 43, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/coala/coalib/settings/SectionFilling.py", line 89, in fill_section
    new_vals = acquire_settings(log_printer, needed_settings, section)

  File "/coala/coalib/output/Interactions.py", line 26, in fail_acquire_settings
    raise AssertionError

AssertionError```

**Comment by Udayan12167** [comment]
Can you give more details. What do you mean by coala 0.8 .coafile. Can you post the .coafile as well?

**Comment by jayvdb** [comment]
I believe this is the same problem that I raised 10 days earlier: https://github.com/coala/coala-bears/issues/1012 

I dont believe more info is needed.  The same `.coafile` that worked in 0.8 is now causing a backtrace in 0.9 . Our own `.coafile` is suitable as a test case for this bug.

**Comment by jayvdb** [comment]
Confirmed this is still a problem in 0.9.1, and is extremely easy to reproduce.

```sh
$ pip install coala-bears
Collecting coala-bears
  Downloading coala_bears-0.9.1-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 1.1MB/s 
Collecting coala
  Using cached coala-0.9.0-py3-none-any.whl
...
Installing collected packages: coala, coala-bears
Successfully installed coala-0.9.0 coala-bears-0.9.1
$ cd coala
$ git checkout release/0.8
$ coala-ci
WARNING:root:Use of `coala-ci` binary is deprecated, use `coala --non-interactive` instead.
[ERROR][18:58:06] During execution, we found that some required settings were not provided. They are:
language (from AnnotationBear) -  The programming language of the source code.
[ERROR][18:58:06] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][18:58:06] Exception was:
```
```python
Traceback (most recent call last):

  File "/usr/lib/python3.5/site-packages/coalib/coala_main.py", line 74, in run_coala
    arg_list=arg_list)

  File "/usr/lib/python3.5/site-packages/coalib/settings/ConfigurationGathering.py", line 362, in gather_configuration
    log_printer)

  File "/usr/lib/python3.5/site-packages/coalib/settings/SectionFilling.py", line 43, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/usr/lib/python3.5/site-packages/coalib/settings/SectionFilling.py", line 89, in fill_section
    new_vals = acquire_settings(log_printer, needed_settings, section)

  File "/usr/lib/python3.5/site-packages/coalib/output/Interactions.py", line 26, in fail_acquire_settings
    raise AssertionError

AssertionError
```

**Comment by jayvdb** [comment]
For the coala `.coafile`, the problem is it uses `KeywordBear`, which depends on `AnnotationBear`.

```ini
[TODOS]
enabled = False

bears = KeywordBear

ci_keywords, keywords = \#TODO, \# TODO, \#FIXME, \# FIXME
cs_keywords =
```

All bears that depend on  `AnnotationBear`:

- `IndentationBear`
- `KeywordBear`
- `QuotesBear`

In 0.8, `IndentationBear` had a `language` parameter, but `KeywordBear` and `QuotesBear` did not, so any use of `KeywordBear` and `QuotesBear` was broken by release 0.9.  That is not cool for CI systems.

**Comment by jayvdb** [comment]
QuotesBear wasnt in 0.8, so the only source of problems is `KeywordBear`, and its dependency on  `AnnotationBear` was added in coala-bears PR https://github.com/coala/coala-bears/pull/884 .

Breakage isolated ; https://github.com/coala/coala-bears/issues/1012 is where the further analysis and discussion should be.
