### ISSUE TITLE
WARNING: No bears matching 'GitCommitBear' were found. (Raised on dev installation)

### ISSUE THREAD

**Issue by RohanVB** [coala/coala#3152]
The following steps cause this error on mac OSX, I'm unsure if it is reproducible on other operating systems.

1)New virtual env
2)New clone of coala and coala-bears
3)pip3 install coala
4)pip3 install coala-bears
5)sudo python3 setup.py install on coala and coala-bears repos
6)Ran coala, warning.

_Here is the version of coala and coala-bears I am currently using:_

```
cd coala-bears
$ coala --version
0.10.0.dev99999999999999
$ python -c "import bears; print(bears.__version__)"
0.10.0.dev99999999999999
```

```
cd coala
$ python -c "import bears; print(bears.__version__)"
0.9.1

$ coala --version
0.10.0.dev99999999999999

```

_Here is the traceback:_ 

```
[WARNING][16:21:53] Unable to collect bears from /Users/name/VirtualEnvs/virt1/lib/python3.5/site-packages/bears/vcs/git/GitCommitBear.py. Probably the file is malformed or the module code raises an exception.
[INFO][16:21:53] Exception was:
Traceback (most recent call last):

  File "/Users/name/VirtualEnvs/virt1/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Collectors.py", line 125, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/Users/name/VirtualEnvs/virt1/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Collectors.py", line 27, in _import_bears
    types=list):

  File "/Users/name/VirtualEnvs/virt1/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)

  File "/Users/name/VirtualEnvs/virt1/lib/python3.5/site-packages/coala_utils/decorators.py", line 24, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/Users/name/VirtualEnvs/virt1/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)

  File "/Users/name/VirtualEnvs/virt1/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)

  File "/Users/name/VirtualEnvs/virt1/lib/python3.5/site-packages/bears/vcs/git/GitCommitBear.py", line 8, in <module>
    from coalib.misc.ContextManagers import change_directory
```

**Comment by RohanVB** [comment]
Unable to reproduce anymore.

**Comment by RohanVB** [comment]
Solution similar to #3281(see comments) if it occurs for anyone else.
