### ISSUE TITLE
Language KeyError when multiple versions exist and one not requested by all versions identical

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3159]
Fetching an attribute from a Language with multiple versions, such as "Python", throws a AttributeError.

```
>>> from coalib.bearlib.languages.Language import Language
>>> l = Language['Python']
>>> l.extensions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../coalib/bearlib/languages/Language.py", line 340, in __getattr__
    raise AttributeError('You have to specify ONE version of your '
AttributeError: You have to specify ONE version of your language to retrieve attributes for it.
```

The relevant chunk of code

```
    def __getattr__(self, item):
        if len(self.versions) > 1:
            raise AttributeError('You have to specify ONE version of your '
                                 'language to retrieve attributes for it.')
        return self._attributes[item]
```

If the extension is constant, as it is `.py` with Python, it should be accessible.

Then the exception has extra meaning, telling the user that the attribute they are looking for is not consistent across all versions.

Also the exception should be a subclass of `AttributeError`, so it can be detected separately from a Language which doesnt have the desired attribute at all.

**Comment by nemaniarjun** [comment]
Can I take this up?

**Comment by aptrishu** [comment]
@jayvdb Do we even have any such attributes defined in our language definitions which differ over different versions ?

**Comment by jack17529** [comment]
@jayvdb  please assign me this.
