### ISSUE TITLE
UnicodeDecodeError details not logged

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3170]
Following on from https://github.com/coala/coala/issues/488 , now when a non-unicode file is encountered, a warning like the following is emitted.

```
[WARNING][08:14:35] Failed to read file '/usr/src/kernels/linux-git-4.6.x/drivers/staging/rtl8188eu/include/odm.h'. It seems to contain non-unicode characters. Leaving it out.
```

The actual traceback contains important information which should also be logged.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib64/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 1313: invalid start byte
```

And that is, for example, this line;

https://github.com/torvalds/linux/blob/2e41434/drivers/staging/rtl8188eu/include/odm.h#L718 , and github renders the problems with upside down `!`.

Ideally, this can be returned as an actual Result , which can be disabled by any non-unicode files being added to the ignore lists.

**Comment by sils** [comment]
I recall when I ran coala on the linux kernel and it actually crashed on this issue - before we had that warning :)

**Comment by Makman2** [comment]
alright let's append the traceback to the issue :)
--> https://github.com/coala/coala/blob/master/coalib/processes/Processing.py#L256

**Comment by Makman2** [comment]
I wouldn't use a result for that, that would kinda break the architecture of coala. Results are produced by bears, if core components start to produce results, stuff gets even weirder and messier.

**Comment by Makman2** [comment]
Things might change with the file-proxy with lazy file-loading^^

**Comment by sils** [comment]
Yep we can have a bear yielding errors like this

On Dec 28, 2016 9:37 PM, "Mischa Krüger" <notifications@github.com> wrote:

Things might change with the file-proxy with lazy file-loading^^

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/coala/coala/issues/3170#issuecomment-269536996>, or mute
the thread

**Comment by Makman2** [comment]
> Yep we can have a bear yielding errors like this

Though I'm not really sure if that makes sense in 99% of cases^^ If you have some analysis, it needs the file intact anyway, having an additional bear for that is bad and performance waste.

**Comment by bharg** [comment]
Hi, can I work on this bug?

**Comment by ARjunSNair** [comment]
hi can i work on this bug

**Comment by frextrite** [comment]
@jayvdb What's the status of this issue? Just ran coala on the mentioned .h file and coala didn't throw any warnings regarding encoding.

**Comment by C0ffeeMachine** [comment]
may i work on this issue @jayvdb

**Comment by Marco2018** [comment]
hi，I am an enthusiast and newcomer here. I guess it is already in its unicode form, so it can't be decode again. If this issue is still open, may I work on this issue?  Thanks

**Comment by arnav-mandal1234** [comment]
Since this issue is inactive for many days Can I take this? @jayvdb @sils @Makman2

**Comment by gr455** [comment]
Hey, may I know what exactly is required in the warning
