### ISSUE TITLE
pytest plugin xdist.looponfail could not be loaded due to installed py 1.4.26

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3184]
```
Collecting pytest-env~=0.6.0 (from -r test-requirements.txt (line 3))
  Downloading pytest-env-0.6.0.tar.gz
Collecting pytest-mock~=1.1 (from -r test-requirements.txt (line 4))
  Downloading pytest_mock-1.5.0-py2.py3-none-any.whl
Collecting pytest-timeout~=1.0 (from -r test-requirements.txt (line 5))
  Downloading pytest_timeout-1.2.0-py2.py3-none-any.whl
Collecting pytest-xdist~=1.14 (from -r test-requirements.txt (line 6))
  Downloading pytest-xdist-1.15.0.tar.gz (87kB)
...
Collecting pytest~=3.0 (from -r test-requirements.txt (line 7))
  Downloading pytest-3.0.5-py2.py3-none-any.whl (170kB)
...
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.22 in /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages (from pytest-xdist~=1.14->-r test-requirements.txt (line 6))
...
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/config.py", line 1029, in _preparse
    self.pluginmanager.load_setuptools_entrypoints(entrypoint_name)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 515, in load_setuptools_entrypoints
    "Plugin %r could not be loaded: %s!" % (ep.name, e))
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'xdist.looponfail' could not be loaded: (py 1.4.26 (/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages), Requirement.parse('py>=1.4.29'), {'pytest'})!
```
from https://travis-ci.org/jayvdb/coala/builds/182542215

Adding `pip install -U py==1.4.29` beforehand fixes the problem.
But it feels like there is a missing dependency upstream somewhere.

**Comment by Mixih** [comment]
Is this still a problem? Looks like our builds work now(unless you wrote a work around)

**Comment by jayvdb** [comment]
There is a workaround in `.travis.yml`

**Comment by jayvdb** [comment]
I see some possibly related fixes in [the changelog](https://github.com/pytest-dev/py/blob/b59055e/CHANGELOG#L37) for 1.4.29 which explains the pytest dependency.

And now when I remove the explicit `pip install -U py`, it seems to work.

**Comment by jayvdb** [comment]
But super bizare, rst-lint fails : https://travis-ci.org/jayvdb/coala-bears/jobs/187472999#L2783

**Comment by jayvdb** [comment]
Argh, another one, in a sort of different plugin `xdist`.

https://travis-ci.org/jayvdb/coala/jobs/187646988

```python
python3 -m pytest --cov --cov-fail-under=100 --doctest-modules
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2309, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2326, in require
    items = working_set.resolve(reqs, env, installer)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (py 1.4.26 (/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages), Requirement.parse('py>=1.4.29'), {'pytest'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: (py 1.4.26 (/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages), Requirement.parse('py>=1.4.29'), {'pytest'})!
...

```

**Comment by jayvdb** [comment]
The problem is we are listing pytest after the plugins in requirements.txt, specifically https://github.com/pytest-dev/pytest-xdist/issues/105

**Comment by jayvdb** [comment]
Note : pip does not have a dependency resolver : https://github.com/pypa/pip/issues/988
