### ISSUE TITLE
can't run coala with -c param

### ISSUE THREAD

**Issue by sils** [coala/coala#3221]
```
lasse@lsx1 ~/prog/coala/coala (git)-[sils/bfix] % docker run -ti -v $(pwd):/app coala/base coala --files="**/*.py" --bears=PEP8Bear --save -V -c /app
[ERROR][15:31:50] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][15:31:50] Exception was:
Traceback (most recent call last):

  File "/coala/coalib/coala_main.py", line 74, in run_coala
    arg_list=arg_list)

  File "/coala/coalib/settings/ConfigurationGathering.py", line 363, in gather_configuration
    save_sections(sections)

  File "/coala/coalib/settings/ConfigurationGathering.py", line 85, in save_sections
    str(default_section.get('config', Constants.default_coafile)))

  File "/coala/coalib/output/ConfWriter.py", line 22, in __init__
    self.__file = open(self.__file_name, 'w')

IsADirectoryError: [Errno 21] Is a directory: '/app'
WARNING: <coalib.output.ConfWriter.ConfWriter object at 0x7f7099635518> was not closed. Cleaning up automatically. Note that this cleanup may not work on other interpreters and is nondeterministic.
Exception ignored in: <bound method ClosableObject.__del__ of <coalib.output.ConfWriter.ConfWriter object at 0x7f7099635518>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pyprint/ClosableObject.py", line 47, in __del__
    self.close()
  File "/usr/lib/python3.5/site-packages/pyprint/ClosableObject.py", line 33, in close
    self._close()
  File "/coala/coalib/output/ConfWriter.py", line 38, in _close
    self.__file.close()
AttributeError: 'ConfWriter' object has no attribute '_ConfWriter__file'
```

**Comment by meetmangukiya** [comment]
I think `coala` expects a config file and the directory is being passed `app/` as suggested by the `metavar`
```
    config_group.add_argument(
        '-c', '--config', nargs=1, metavar='FILE',
        help='configuration file to be used, defaults to {}'.format(
            Constants.default_coafile))
```

**Comment by sils** [comment]
it should support directories as well, I wrote the support for that

**Comment by meetmangukiya** [comment]
I would like to be assigned..

**Comment by jayvdb** [comment]
With `-c dir`, it should find the .coafile in `dir`, and run with all paths relative to `dir`?

What should `-c .ci/coafile` do, wrt relative paths. Be based on `$CWD`, or relative to `.ci/` ?

Reason is that we could end up with a situation where `-c dir` and `-c dir/coafile` have different results, which would be very confusing.

**Comment by sils** [comment]
don't understand the problem, if there's no leading slash you'll always want it relative so if you give `-c .ci/coafile` it'll be `$(pwd)/.ci/coafile`

**Comment by jayvdb** [comment]
Ah, yes I am referring to running `coala -c /some/other/directory`

**Comment by sils** [comment]
well that would always get the coafile from that absolute path, there's no confusion, right?

**Comment by jayvdb** [comment]
@meetmangukiya , have you worked on this?
Can i give it to a gci?

**Comment by meetmangukiya** [comment]
@jayvdb tbh very little, you may if you want.
