### ISSUE TITLE
crash when runing coala on the libreoffice core repo

### ISSUE THREAD

**Issue by sils** [coala/coala#3701]
coafile:
```
[Default]
bears = CPDBear, CPPCheckBear
files = **.cxx, **.hxx
language = c++
```
log:
```
[DEBUG][23:43:25] Running bear CPDBear...
[WARNING][23:43:25] Bear CPDBear failed to run. Take a look at debug messages (`-V`) for further information.
[DEBUG][23:43:26] The bear CPDBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/home/lasse/venvs/def/lib/python3.5/site-packages/coalib/bears/Bear.py", line 240, in execute
    return [] if result is None else list(result)
  File "/home/lasse/venvs/def/lib/python3.5/site-packages/bears/general/CPDBear.py", line 103, in run
    stdout_output, _ = run_shell_command(arguments)
  File "/home/lasse/venvs/def/lib/python3.5/site-packages/coalib/misc/Shell.py", line 103, in run_shell_command
    with run_interactive_shell_command(command, **kwargs) as p:
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/lasse/venvs/def/lib/python3.5/site-packages/coalib/misc/Shell.py", line 70, in run_interactive_shell_command
    process = Popen(command, **args)
  File "/usr/lib64/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 7] Argument list too long
```

**Comment by sils** [comment]
my(max) idea is that we might try to run cpd with 10k files and it doesn't like that

**Comment by Makman2** [comment]
looks even like it's a limit inside python (or even OS) :O
That's bad actually...

If possible, maybe CPD supports configuration files where you can also put the files to analyze?

**Comment by sims1253** [comment]
there is --files for files and directories. Maybe we can bundle the files somehow or add directories

**Comment by sims1253** [comment]
actually there is "There should be no limit to the number of ‘–files’, you may add… But if you stumble one, please tell us !" in their docs

**Comment by impmihai** [comment]
[Errno 7] Argument list too long
This is an OS related issue as i can read. Maybe splitting into multiple runs of coala over smaller ammounts of files would help?

**Comment by Makman2** [comment]
Problem is you may loose context when splitting up files^^

**Comment by Makman2** [comment]
But it's definitely a limit in python / OS:
```
>>> call(['echo'] + list(str(x) for x in range(1000000)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 7] Argument list too long
```

**Comment by Makman2** [comment]
So we need a configuration file, where we can put an arbitrary amount of information.

**Comment by Makman2** [comment]
Interesting, just tested it: It's a limit in Python, not the OS!
Bash supports as many arguments as needed, I generated a bash file with `echo 1 2 3 ...` until 1000000 (one million), and it echoes properly^^

**Comment by sims1253** [comment]
so then subprocess has a limeted amount of parameters you can give it? strange
If we could somehow give it directories instead of files that would maybe obscure the problem by shrinking the list length

**Comment by Makman2** [comment]
but still we want to support passing in specific files, and if the user wants 10000+ specific files, then we have this problem again^^

**Comment by impmihai** [comment]
maybe writing down the parameters to a temporary file and read them from there?

**Comment by impmihai** [comment]
Ok, looks like the old version of CPD that circleCI has does not have the --filelist option that takes a file containing the filelist to run on. We need to update PMD on CI, am i right?

**Comment by impmihai** [comment]
Ok, it is worse than i thought. Pmd has been updated with the -filelist option, but cpd does not have that. All i can do is to file an issue to pmd to add that feature to cpd too. Shall I do this and wait for an update?

**Comment by jayvdb** [comment]
Yes please raise the bug upstream

**Comment by impmihai** [comment]
I made a PR to PMD in order to add that option. Here it is: https://github.com/pmd/pmd/pull/297 . When it is merged, i will finish the PR on this issue. ☺️

**Comment by impmihai** [comment]
PR merged, waiting for their version release and I am ready to finish this too 😄

**Comment by jayvdb** [comment]
https://github.com/pmd/pmd/commit/029ed7c7a isnt in the latest release [v5.5.5](https://github.com/pmd/pmd/releases/tag/pmd_releases%2F5.5.5), so it looks like this will be in v5.6.

https://pmd.github.io/ says that 5.5.5 will be the last release in the 5.5 series, so 5.6 is probably on the way soon, and it has only [two blockers not yet done](https://sourceforge.net/p/pmd/bugs/milestone/PMD-5.6.0/).

**Comment by jayvdb** [comment]
5.6 has been released, and includes this feature. https://pmd.github.io/pmd-5.6.0/overview/changelog.html
