### ISSUE TITLE
TypeError in Linter.run with --settings

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3796]
A `TypeError` is generated from the following command line in the coala-bears directory

```
$  coala-ci -I --bears CheckstyleBear --files ./tests/java/test_files/CheckstyleGood.java -V --settings checkstyle_configs=geosoft
WARNING:root:Use of `coala-ci` binary is deprecated, use `coala --non-interactive` instead.
[DEBUG][21:33:52] Platform Linux -- Python 3.6.0, coalib 0.10.0.dev99999999999999
[DEBUG][21:33:52] Since the configuration settings have changed since the last run, the cache will be flushed and rebuilt.
[DEBUG][21:33:52] The file cache was successfully flushed.
Executing section cli...
[DEBUG][21:33:52] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][21:33:52] Files that will be checked:
/../coala-bears/tests/java/test_files/CheckstyleGood.java
[DEBUG][21:33:52] Running bear CheckstyleBear...
[WARNING][21:33:52] Bear CheckstyleBear failed to run on file /../coala/coala-bears/tests/java/test_files/CheckstyleGood.java. Take a look at debug messages (`-V`) for further information.
[DEBUG][21:33:52] The bear CheckstyleBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/../coala/coalib/bears/Bear.py", line 250, in execute
    result = self.run_bear_from_section(args, kwargs)
  File "/../coala/coalib/bears/Bear.py", line 243, in run_bear_from_section
    return self.run(*args, **kwargs)
  File "/../coala/coalib/bearlib/abstractions/Linter.py", line 550, in run
    self.debug("Running '{}'".format(' '.join(arguments)))
TypeError: sequence item 2: expected str instance, NoneType found
```

I believe it should have behind the scenes set `cli.checkstyle_configs=geosoft`, and maybe emitted a deprecation notice, but adding the `cli.` prefix is quite redundant.

**Comment by jayvdb** [comment]
I suspect this is a regression.

**Comment by Techievena** [comment]
@jayvdb getting this result:
```
abinash (master) coala-bears $ coala-ci -I --bears CheckstyleBear --files ./tests/java/test_files/CheckstyleGood.java -V --settings checkstyle_configs=geosoft --flush-cache
WARNING:root:Use of `coala-ci` binary is deprecated, use `coala --non-interactive` instead.
[DEBUG][06:56:26] Platform Linux -- Python 3.5.2, coalib 0.10.0.dev99999999999999
[DEBUG][06:56:26] The file cache was successfully flushed.
Executing section cli...
[DEBUG][06:56:26] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][06:56:26] Files that will be checked:
/home/abinash/gsoc2017/coala-bears/tests/java/test_files/CheckstyleGood.java
[DEBUG][06:56:26] Running bear CheckstyleBear...
[DEBUG][06:56:26] Running 'java -jar /home/abinash/.local/share/coala-bears/CheckstyleBear/checkstyle.jar -c /home/abinash/.local/share/coala-bears/CheckstyleBear/geosoft.xml /home/abinash/gsoc2017/coala-bears/tests/java/test_files/CheckstyleGood.java'
```

**Comment by jayvdb** [comment]
hmm.  I cant reproduce it either now. :/
