### ISSUE TITLE
cib install fails

### ISSUE THREAD

**Issue by KenjiTakahashi** [coala/coala#3938]
Installed with (also tried with python3.5, just in case, same thing):
```bash
 ~/ mkvirtualenv -p python3 coala
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/kenji/.virtualenvs/coala/bin/python3.6
Also creating executable in /Users/kenji/.virtualenvs/coala/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/kenji/.virtualenvs/coala/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/kenji/.virtualenvs/coala/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/kenji/.virtualenvs/coala/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/kenji/.virtualenvs/coala/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/kenji/.virtualenvs/coala/bin/get_env_details
(coala)  ~/ pip --version
pip 9.0.1 from /Users/kenji/.virtualenvs/coala/lib/python3.6/site-packages (python 3.6)
(coala)  ~/ pip install coala cib
Collecting coala
  Using cached coala-0.10.0-py34.py35.py36-none-any.whl
Collecting cib
Collecting dependency-management~=0.3.1 (from coala)
  Using cached dependency_management-0.3.1-py3-none-any.whl
Collecting libclang-py3~=3.4.0 (from coala)
Collecting colorlog~=2.7 (from coala)
  Using cached colorlog-2.10.0-py2.py3-none-any.whl
Requirement already satisfied: appdirs~=1.4 in ./.virtualenvs/coala/lib/python3.6/site-packages (from coala)
Collecting Pygments~=2.1 (from coala)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting requests~=2.12 (from coala)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting PyPrint~=0.2.6 (from coala)
  Using cached PyPrint-0.2.6-py3-none-any.whl
Collecting coala-utils~=0.6.0 (from coala)
  Using cached coala_utils-0.6.2-py3-none-any.whl
Collecting termcolor==1.1.0 (from cib)
Collecting docopt==0.6.2 (from cib)
Collecting sarge~=0.1.4 (from dependency-management~=0.3.1->coala)
Collecting colorama~=0.3.7 (from PyPrint~=0.2.6->coala)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Installing collected packages: coala-utils, sarge, dependency-management, libclang-py3, colorlog, Pygments, requests, termcolor, colorama, PyPrint, coala, docopt, cib
Successfully installed PyPrint-0.2.6 Pygments-2.2.0 cib-0.5.7 coala-0.10.0 coala-utils-0.6.2 colorama-0.3.7 colorlog-2.10.0 dependency-management-0.3.1 docopt-0.6.2 libclang-py3-3.4.0 requests-2.13.0 sarge-0.1.4 termcolor-1.1.0
```
Trying to use cib:
```bash
(coala)  ~/ cib install PEP8Bear
PEP8Bear is installing...  Traceback (most recent call last):
  File "/Users/kenji/.virtualenvs/coala/bin/cib", line 11, in <module>
    sys.exit(main())
  File "/Users/kenji/.virtualenvs/coala/lib/python3.6/site-packages/coala_package_manager/installation_tool.py", line 216, in main
    args['--ignore-deps'])
  File "/Users/kenji/.virtualenvs/coala/lib/python3.6/site-packages/coala_package_manager/installation_tool.py", line 144, in install_bears
    if not PipRequirement(bear_name).install_package():
AttributeError: 'PipRequirement' object has no attribute 'install_package'
```
Tried several different bears, same result.

**Comment by Madhukar-SH** [comment]
@KenjiTakahashi  This bug can basically be fixed by replacing the '/lib/python3.x/site_packages/dependency_management' with the latest edition of 'coala_package_manager' from the repo https://gitlab.com/coala/package_manager
Becaue when cib is installed with pip3, its installing from outdated repo, in which the PipRequirement.py does not have install_package() function, where as the lastest repo has the install_package() function.

**Comment by KenjiTakahashi** [comment]
Maybe it's time for a new release then :-)? For now I just installed bears with pip directly. I only needed the Python ones (for now), so it was not a problem.

**Comment by Makman2** [comment]
yeah that should be included in the release as this is something a user (and also me) would expect to work right out of the box.

@Mixih you are release team leader if I recall correctly ;)

**Comment by jayvdb** [comment]
`cib` is only mentioned on the page `Bear_Installation_Tool.rst`.  IMO that page should note that `cib` is a work in progress, or it should be removed / replaced with a link to the cib repository.

When it is actually working, `cib` documentation would belong in the [User documentation](https://github.com/coala/documentation), so it isnt particularly helpful to keep it (with the current content) in the developer docs of `coala/coala`.

**Comment by jsecrest** [comment]
Has an issue been created for fixing the [Bear Installation Tool](https://api.coala.io/en/latest/Developers/Bear_Installation_Tool.html) documentation? I lost several hours trying to get CIB to work and had to do some digging to find this issue. The bear installation tool is the top result on google when I search "coala install bears," so I can imagine that I'm not the first or last newcomer that will be thrown a curve ball by this.

**Comment by anctartica** [comment]
yes cib is currently not working.. requires some modification but it will at least functional very soon
