### ISSUE TITLE
collectors: get_all_bears raises AttributeError 

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#4021]
`get_all_bears` function doesn't take any argument. So, it should work this way IMO

Code: 
```py
In [1]: from coalib.collecting.Collectors import get_all_bears, get_all_bears_names
 
In [2]: get_all_bears()
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/phoenista/Desktop/ghubby/coala/coala-main/coalib/settings/Section.py in get(self, key, default, ignore_defaults)
    234         try:
--> 235             return self.__getitem__(key, ignore_defaults)
    236         except IndexError:
 
/home/phoenista/Desktop/ghubby/coala/coala-main/coalib/settings/Section.py in __getitem__(self, item, ignore_defaults)
    213         if self.defaults is None or ignore_defaults:
--> 214             raise IndexError('Required index is unavailable.')
    215
 
IndexError: Required index is unavailable.
 
During handling of the above exception, another exception occurred:
 
AttributeError                            Traceback (most recent call last)
<ipython-input-2-ee36147e61f7> in <module>()
----> 1 get_all_bears()
 
/home/phoenista/Desktop/ghubby/coala/coala-main/coalib/collecting/Collectors.py in get_all_bears()
    239     printer = LogPrinter(NullPrinter())
    240     local_bears, global_bears = collect_bears(
--> 241         Section('').bear_dirs(),
    242         ['**'],
    243         [BEAR_KIND.LOCAL, BEAR_KIND.GLOBAL],
 
/home/phoenista/Desktop/ghubby/coala/coala-main/coalib/settings/Section.py in bear_dirs(self)
    107
    108     def bear_dirs(self):
--> 109         bear_dirs = path_list(self.get('bear_dirs', ''))
    110         for bear_dir in bear_dirs:
    111             sys.path.append(bear_dir)
 
/home/phoenista/Desktop/ghubby/coala/coala-main/coalib/settings/Section.py in get(self, key, default, ignore_defaults)
    235             return self.__getitem__(key, ignore_defaults)
    236         except IndexError:
--> 237             return Setting(key, str(default))
    238
    239     def copy(self):
 
/home/phoenista/Desktop/ghubby/coala/coala-main/coalib/settings/Setting.py in __init__(self, key, value, origin, strip_whitespaces, list_delimiters, from_cli, remove_empty_iter_elements, to_append)
    140             strip_whitespaces=strip_whitespaces,
    141             list_delimiters=list_delimiters,
--> 142             remove_empty_iter_elements=remove_empty_iter_elements)
    143
    144         self.from_cli = from_cli
 
/usr/lib/python3.5/site-packages/coala_utils/string_processing/StringConverter.py in __init__(self, value, strip_whitespaces, list_delimiters, dict_delimiter, remove_empty_iter_elements)
     34         self.__unescaped_list = None
     35         self.__dict = None
---> 36         self.value = value
     37
     38     def __str__(self):
 
/usr/lib/python3.5/site-packages/coala_utils/string_processing/StringConverter.py in value(self, newval)
    148             self.__value = unescaped_strip(self.__value)
    149
--> 150         self.__prepare_list()
    151         self.__prepare_dict()
    152
 
/usr/lib/python3.5/site-packages/coala_utils/string_processing/StringConverter.py in __prepare_list(self)
    102
    103     def __prepare_list(self):
--> 104         self.__escaped_list = self.__get_raw_list()
    105
    106         if self.__strip_whitespaces:
 
/usr/lib/python3.5/site-packages/coala_utils/string_processing/StringConverter.py in __get_raw_list(self)
     98
     99         return list(unescaped_split(pattern,
--> 100                                     self.value,
    101                                     use_regex=True))
    102
 
/home/phoenista/Desktop/ghubby/coala/coala-main/coalib/settings/Setting.py in value(self)
    243                              'incomplete. Please access the value of the '
    244                              'setting in a section to get the complete value.')
--> 245         return self._value
 
AttributeError: 'Setting' object has no attribute '_value'
```

**Comment by vasramc** [comment]
I cannot reproduce this, what version of coala are you using? Also mention the python version you are using.

**Comment by adhikasp** [comment]
Working as expected here, python v3.6 with latest coala master branch.

**Comment by jayvdb** [comment]
I get

```
python3 -c 'from coalib.collecting.Collectors import get_all_bears, get_all_bears_names; get_all_bears(); get_all_bears_names();'
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
Call stack:
  File "<string>", line 1, in <module>
  File ".../coalib/collecting/Collectors.py", line 245, in get_all_bears
    warn_if_unused_glob=False)
  File ".../coalib/collecting/Collectors.py", line 170, in collect_bears
    for bear, glob in icollect_bears(bear_dirs, bear_globs, kinds, log_printer):
  File "/usr/lib/python3.6/site-packages/coala_utils/decorators.py", line 24, in yield_once_generator
    for item in iterator(*args, **kwargs):
  File ".../coalib/collecting/Collectors.py", line 129, in icollect_bears
    for bear in _import_bears(matching_file, kinds):
  File ".../coalib/collecting/Collectors.py", line 27, in _import_bears
    types=list):
  File ".../coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)
  File "/usr/lib/python3.6/site-packages/coala_utils/decorators.py", line 24, in yield_once_generator
    for item in iterator(*args, **kwargs):
  File ".../coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)
  File ".../coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "...-bears/bears/css/StyleLintBear.py", line 11, in <module>
    config_suffix='.json')
  File ".../coalib/bearlib/abstractions/Linter.py", line 158, in _create_linter
    _prepare_options(options, klass)
  File ".../coalib/bearlib/abstractions/Linter.py", line 85, in _prepare_options
    .format(bear_class.__name__))
Message: "StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex."
Arguments: ()
```

**Comment by adhikasp** [comment]
The exact same command works on me
```sh
$ python3 -c 'from coalib.collecting.Collectors import get_all_bears, get_all_bears_names; get_all_bears(); get_all_bears_names();'
WARNING:root:StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
DEBUG:pip.vcs:Registered VCS backend: git
DEBUG:pip.vcs:Registered VCS backend: hg
DEBUG:pip.vcs:Registered VCS backend: svn
DEBUG:pip.vcs:Registered VCS backend: bzr
