### ISSUE TITLE
Semantics in Language.py

### ISSUE THREAD

**Issue by MariosPanag** [coala/coala#4048]
### Overview Description
I was working on this issue https://github.com/coala/coala/issues/4037 about writing a test suite for Languages class of Language.py file and I noticed that the __eq__ behavior is changed and calls limit_versions but this causes a problem because there are Languages (CSharp,Java etc) in definitions folder that dont have the attribute versions so if you go and compare for example Language['C#'] == Language["C#"] this will fail because C# hasnt any versions so it will raise an error.

# Steps to Reproduce
```from coalib.bearlib.languages.Language import Language, LanguageMeta, Languages```
```Language['C#'] == Language["C#"]```
```
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    Language['C#'] == Language["C#"]
  File "C:\Users\Gr33nPeArL\Desktop\Project-COALA\Coala_Environment\coala\coalib\bearlib\languages\Language.py", line 381, in __eq__
    return limit_versions(self, other, operator.eq)
  File "C:\Users\Gr33nPeArL\Desktop\Project-COALA\Coala_Environment\coala\coalib\bearlib\languages\Language.py", line 436, in limit_versions
    raise ValueError('No versions left')
ValueError: No versions left
```

For example if  you add ```versions = 2.7, 3.3, 3.4, 3.5, 3.6 in CSharp``` you won't get that error.
# Suggestions
So I believe that we shouldn't overload the == operator but  1) instead we should add a new method to limit versions or 2) keep it this way but add versions to other Languages or 3)change the behavior of limit_versions to work without versions as well.

**Comment by MariosPanag** [comment]
By the way after we discuss about the solution i would like to assign to it and implement it if that's okay !
