### ISSUE TITLE
Unhandled exception PermissionDenied reading .coarc

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4110]
If the user does not have permission to read .coarc, an ugly unhandled exception occurs.

```
[ERROR][09:49:41] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:

[INFO][09:49:41] Exception was:
Traceback (most recent call last):
  File "/coala/coalib/coala_main.py", line 81, in run_coala
    arg_list=arg_list)
  File "/coala/coalib/settings/ConfigurationGathering.py", line 384, in gather_configuration
    sections, targets = load_configuration(arg_list, log_printer, arg_parser)
  File "/coala/coalib/settings/ConfigurationGathering.py", line 171, in load_configuration
    silent=True)
  File "/coala/coalib/settings/ConfigurationGathering.py", line 58, in load_config_file
    return ConfParser().parse(filename)
  File "/coala/coalib/parsing/ConfParser.py", line 51, in parse
    with open(input_data, 'r', encoding='utf-8') as _file:
PermissionError: [Errno 13] Permission denied: '/root/.coarc'
```

The exception should be caught (in ConfigurationGathering) and an ordinary error message logged in the system.

**Comment by ai-coder** [comment]
Can I take this

**Comment by jayvdb** [comment]
no.
ping @madhukar01 , could you add tests to your PR so it can be finished.

**Comment by shreyateeza** [comment]
If no one is working on this issue, please assign this to me

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by shreyateeza** [comment]
Someone please let me know the location of this file.

**Comment by Makman2** [comment]
> The exception should be caught (in ConfigurationGathering) and an ordinary error message logged in the system.

**Comment by vddesai1998** [comment]
Hey, @shreyateeza if you are not working on this issue can I take this one?

**Comment by shreyateeza** [comment]
I am currently working on this issue. Feel free to take another issue @vddesai1998

**Comment by shreyateeza** [comment]
@jayvdb  Please unassign me from this issue. I am no longer working on this. :sweat_smile:
