### ISSUE TITLE
ConsoleInteractionTest starts editor if run with .misc/test.py

### ISSUE THREAD

**Issue by thisch** [coala/coala#4184]
If I run pytest using `bash .misc/test.sh`, my editor (gui version of emacs) is started in the ConsoleInterationTest. This should not happen.

```
++ python -c 'import platform; print(platform.system())'
+ export PLATFORM_SYSTEM=Linux
+ PLATFORM_SYSTEM=Linux
++ python -c 'import os; print(os.name)'
+ export OS_NAME=posix
+ OS_NAME=posix
+ python -m pytest
====================================================================================================== test session starts =======================================================================================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/thomas/gitrepos/coala, inifile: setup.cfg
plugins: xdist-1.16.0, timeout-1.2.0, mock-1.6.0, env-0.6.0, cov-2.4.0
timeout: 35.0s method: signal
collected 707 items 

coalib/bearlib/__init__.py ..
....
tests/output/ConsoleInteractionTest.py
```

**Comment by Makman2** [comment]
Actually I'm not sure whether we support to run the CI stuff locally. If you want to test, just run `py.test` instead of using the CI scripts. Might be that we spawn up an editor on purpose^^

**Comment by thisch** [comment]
We do support it according to the docs (see e.g. https://github.com/coala/coala/pull/4176#issuecomment-299723478). This issue can also be reproduced if I run pytest directly

```
pytest --verbose tests/output/ConsoleInteractionTest.py::ConsoleInteractionTest::test_print_result
```

**Comment by Makman2** [comment]
Oh then it's bad :/

**Comment by thisch** [comment]
If I unset the EDITOR env var, I get (I don't know if this is related, though)

```
tests/testing/LocalBearTestHelperTest.py .......
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/_pytest/main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/_pytest/main.py", line 133, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/pytest_cov/plugin.py", line 232, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/pytest_cov/engine.py", line 150, in finish
INTERNALERROR>     self.cov.combine()
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/coverage/control.py", line 778, in combine
INTERNALERROR>     self.data, aliases=aliases, data_paths=data_paths, strict=strict,
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/coverage/data.py", line 728, in combine_parallel_data
INTERNALERROR>     data.update(new_data, aliases=aliases)
INTERNALERROR>   File "/home/thomas/gitrepos/coala_venv/lib/python3.6/site-packages/coverage/data.py", line 481, in update
INTERNALERROR>     raise CoverageException("Can't combine line data with arc data")
INTERNALERROR> coverage.misc.CoverageException: Can't combine line data with arc data
```

**Comment by Makman2** [comment]
I also encountered recently problems with merging line and arc data on my test runs. Though interesting that this only occurs for you if you unset the `EDITOR` variable... I definitely have no ideas :/
