### ISSUE TITLE
Unknown error exception with CSecurityBear

### ISSUE THREAD

**Issue by mrbkt** [coala/coala#4193]
### Overview Description

Running `CSecurityBear` on large source repo via Docker yields unknown error exception. 

# Steps to Reproduce

1. `git clone --depth 1 https://github.com/torvalds/linux.git`
1. `docker run -it -v $(pwd):/app --workdir=/app coala/base coala --json --files=**/*.c -o csecurity-linux.json --bears=CSecurityBear --save`

# Actual Results

```
[ERROR][02:12:03] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][02:12:03] Exception was:
Traceback (most recent call last):

  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 749, in _callmethod
    conn = self._tls.connection

AttributeError: 'ForkAwareLocal' object has no attribute 'connection'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/coala/coalib/coala_main.py", line 113, in run_coala
    console_printer=console_printer)

  File "/coala/coalib/processes/Processing.py", line 730, in execute_section
    console_printer=console_printer),

  File "/coala/coalib/processes/Processing.py", line 566, in process_queues
    result_files.update(get_file_list(local_result_dict[index]))

  File "<string>", line 2, in __getitem__

  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 753, in _callmethod
    self._connect()

  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 740, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)

  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)

  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)

ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 247, in _feed
    send_bytes(obj)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

# Expected Results

Completed run with results written to JSON file.

# Reproducibility

Consistent.

# Additional Information:

macOS Sierra with full Coala Docker installation

**Comment by Makman2** [comment]
Can't reproduce, coala runs through on my machine:
```
ak  ~  TEMP  docker run -it -v $(pwd):/app:Z --workdir=/app coala/base coala --json --files=**/*.c -o csecurity-linux.json --bears=CSecurityBear --save
[WARNING][12:17:58] Failed to read file '/app/linux/kernel/events/callchain.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:17:58] Failed to read file '/app/linux/lib/fonts/font_pearl_8x8.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:17:58] Failed to read file '/app/linux/lib/fonts/font_8x8.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:17:58] Failed to read file '/app/linux/lib/fonts/font_7x14.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:17:58] Failed to read file '/app/linux/lib/fonts/font_8x16.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:17:59] Failed to read file '/app/linux/arch/arm/crypto/sha256_neon_glue.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:17:59] Failed to read file '/app/linux/arch/arm/crypto/sha256_glue.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:18:00] Failed to read file '/app/linux/arch/s390/kernel/ebcdic.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:18:01] Failed to read file '/app/linux/drivers/iio/dac/ltc2632.c'. It seems to contain non-unicode characters. Leaving it out.
[WARNING][12:18:05] Failed to read file '/app/linux/drivers/power/reset/ltc2952-poweroff.c'. It seems to contain non-unicode characters. Leaving it out.
 mak  ~  TEMP  
```
What are your machine specs? My coala run on docker required about 3GB of RAM. Maybe your machine did run out of it^^ (would kind of explain the broken pipe for me: memory exception -> program killed -> pipe not closed properly and breaks -> python on the other side of the pipe goes crazy)

**Comment by mrbkt** [comment]
Mac Pro 32GB RAM.  macOS Sierra 10.12.4.  Docker 17.05.0-ce-rc1. 

I have see this error/exception on large runs with other Bears as well.  I will capture more evidence.

**Comment by Makman2** [comment]
Okay looks not like RAM...  and I have also the same docker version except that it's not release candidate (`rc1`).

But looking at the error again, maybe you have policy problems with docker? As I see `ConnectionRefusedError`. And did the error appear immediately after you started the run with docker? Or did it take a while?

**Comment by jayvdb** [comment]
Just noting, this looks eerily like a closed Python bug : https://bugs.python.org/issue3419 , and there are very few other Google hits.  You are not seeing the same bug, but it does suggest you are seeing an out of memory (OOM) problem in the docker, as OOM will cause all sorts of strange failures not normally seen.

**Comment by mrbkt** [comment]
Sorry guys, this one is now not exactly reproducible for me too.  Today I can cause a different outcome, `BrokenPipeError: [Errno 32] Broken pipe`, running the same way on different repos with this bear or with the `ClangBear`.  It appears to be a Docker issue and related to resource utilization and much container detritus from prior runs.  I am happy if you'd like to close this issue as curious but not reproducible.

**Comment by Makman2** [comment]
Would be still interesting what circumstances in docker do prevent coala from running :)

**Comment by mrbkt** [comment]
I would too.  I have more work to do to isolate the conditions.  If I can identify I will be happy to post them here.
