### ISSUE TITLE
Unknown exception

### ISSUE THREAD

**Issue by plaindocs** [coala/coala#4208]
Hey Coalas,

Brand new bug here:

https://travis-ci.org/travis-ci/docs-travis-ci-com/jobs/230418873

```
$ coala --non-interactive Language
[ERROR][16:38:59] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][16:38:59] Exception was:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2801, in _dep_map
    return self.__dep_map
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2658, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/coalib/coala_main.py", line 80, in run_coala
    arg_list=arg_list)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/coalib/settings/ConfigurationGathering.py", line 363, in gather_configuration
    log_printer)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/coalib/settings/SectionFilling.py", line 31, in fill_settings
    bear_dirs = section.bear_dirs()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/coalib/settings/Section.py", line 74, in bear_dirs
    for bear_dir in collect_registered_bears_dirs('coalabears')]
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/coalib/collecting/Collectors.py", line 303, in collect_registered_bears_dirs
    registered_package = ep.load()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 847, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2602, in requires
    dm = self._dep_map
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2803, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2836, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2833, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'platform_system' is not defined
```

**Comment by Makman2** [comment]
I'm just encountering the same issues on our CI (except on CircleCI).
--> https://ci.appveyor.com/project/coala/coala/build/1.0.7679/job/999l13y8kxc9r00b

**Comment by plaindocs** [comment]
Googling `NameError: name 'platform_system' is not defined` led me to install `setuptools` but that didn't help.

**Comment by Makman2** [comment]
Maybe downgrading `setuptools` helps as we currently specify `setuptools>=17.0`.

**Comment by plaindocs** [comment]
`  - pip install 'setuptools==17.0'` does seem to resolve my issue.

**Comment by Makman2** [comment]
Okay then this is definitely an upstream bug in setuptools. So we need to limit `setuptools` to the most recent version that works.

**Comment by jayvdb** [comment]
I think this is one case where we blacklist known problem versions.

**Comment by stellargo** [comment]
After having a look at recent appveyor builds, I think this issue is back :P

**Comment by Makman2** [comment]
On AppVeyor `setuptools==19` seems to work, `setuptools==18.2` didn't work. Maybe 18.x was a problem-series^^

**Comment by jayvdb** [comment]
We do testing now with setuptools 21.2.2

We could implement a hack to get lower versions working reliably.

c.f. https://github.com/moremoban/pypi-mobans/commit/9df26827578d25131a2c08e1876437b3f5de1a2c , for links to other projects using this hack.

Also https://github.com/moremoban/moban/commit/5e895b6a9e3a7b06c3cbd3ea651b197990366c33#diff-2eeaed663bd0d25b7e608891384b7298
