### ISSUE TITLE
Travis CI is failing

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4218]
https://travis-ci.org/coala/coala/jobs/231250070#L1052

Some `BadZipFile` error.

**Comment by jayvdb** [comment]
```
$ pip install coala-bears[alldeps] --pre -U
...
Collecting language-check~=1.0; extra == "alldeps" (from coala-bears[alldeps])
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/pip/utils/__init__.py", line 484, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/opt/python/3.6.1/lib/python3.6/zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "/opt/python/3.6.1/lib/python3.6/zipfile.py", line 1168, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by jayvdb** [comment]
It was a broken zip file in the Travis CI cache.  All caches deleted.
