### ISSUE TITLE
sphinx-build fails on docutils 0.14rc1

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4280]
docutils released a version `0.14rc1` resulting in
```
sphinx-build -b html -d _build/doctrees  -W . _build/html
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.1/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/sphinx/__init__.py", line 61, in build_main
    from sphinx import cmdline
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/sphinx/cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/sphinx/application.py", line 35, in <module>
    from sphinx.domains import ObjType, BUILTIN_DOMAINS
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/sphinx/domains/__init__.py", line 281, in <module>
    from sphinx.domains.cpp import CPPDomain                 # noqa
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/sphinx/domains/cpp.py", line 24, in <module>
    from sphinx.util.compat import Directive
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/sphinx/util/compat.py", line 17, in <module>
    docutils_version = tuple(int(x) for x in _du_version.split('.')[:2])
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/sphinx/util/compat.py", line 17, in <genexpr>
    docutils_version = tuple(int(x) for x in _du_version.split('.')[:2])
ValueError: invalid literal for int() with base 10: '14rc1'
make: *** [html] Error 1
```

**Comment by jayvdb** [comment]
Note that https://github.com/sphinx-doc/sphinx/pull/3677 removed this chuck of code from master, to be part of v1.7.

They have a `stable` branch for 1.6, so maybe they are interested in this fix.

https://github.com/sphinx-doc/sphinx/blob/stable/sphinx/__init__.py#L37

But I guess they will want the problem fixed upstream also, which can be done by removing the problematic rc, and will also be fixed when the rc becomes a proper release.

**Comment by jayvdb** [comment]
This was resolved upstream
