### ISSUE TITLE
circle.yml: Don't use pip install coala-bears[alldeps] --pre -U

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4311]
Because we also get pre-releases of all dependencies that way, which can cause issues like https://github.com/coala/coala/pull/4276#issuecomment-305808190

```
sphinx-build -b html -d _build/doctrees  -W . _build/html
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.5.1/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sphinx/__init__.py", line 66, in main
    sys.exit(build_main(argv))
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sphinx/__init__.py", line 76, in build_main
    from sphinx import cmdline
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sphinx/cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sphinx/application.py", line 36, in <module>
    from sphinx.domains.std import GenericObject, Target, StandardDomain
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sphinx/domains/std.py", line 27, in <module>
    from sphinx.util.compat import Directive
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sphinx/util/compat.py", line 19, in <module>
    docutils_version = tuple(int(x) for x in _du_version.split('.')[:2])
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sphinx/util/compat.py", line 19, in <genexpr>
    docutils_version = tuple(int(x) for x in _du_version.split('.')[:2])
ValueError: invalid literal for int() with base 10: '14rc1'
```

Better use two steps:

```
- pip install coala-bears[alldeps] -U
- pip install coala-bears --pre -U --no-deps
```

**Comment by jayvdb** [comment]
@userzimmermann , your suggestion to use two commands will result

1. slower CI, due to two different versions of coala & coala-bears & dependencies being installed as it first installs the released version and then installs the pre-release version
2. will result in master being unusable, because sometimes the release version is not installable.  Patches to fix releases are first reviewed on master, this creates a catch 22.
3. maintainers not learning about problems with pre-releases of dependencies early.  Bugs like you encountered are actually a really good thing.  The proper procedure is to create a local issue, investigate it properly, and then work with upstream if necessary to resolve it.  We need more maintainers and developers who can do this.  Whether we like it or not, our users do upgrade other dependencies, and we need to know early when they fail.  And an upstream pre-release will become a release, and if there is a bug we *need* to know about them to prevent them being released broken.
4. Our users following our documentation will encounter problems before developers have encountered them.  That is not helpful.

```
coala/documentation> $ git grep '[-]-pre'
Users/Install.rst:    $ pip3 install coala-bears --pre
Users/Install.rst:    $ pip3 install coala-bears --pre
Users/Install.rst:``python3 setup.py install --prefix=/your/prefix/location``. Other installation

coala/coala> $ git grep '[-]-pre'
.misc/deploy.pypi.sh:pip3 install --pre coala==`cat coalib/VERSION` --upgrade
.travis.yml:  - pip install coala-bears[alldeps] --pre -U
RELEASE_NOTES.rst:   via ``pip install coala --pre``.
circle.yml:    - pip install coala-bears[alldeps] --pre -U:
```

There are solutions for some of the above problems that will require some development first, and we can change our docs, but we need to evaluate this properly.
