### ISSUE TITLE
coala --ci fails on Travis

### ISSUE THREAD

**Issue by singhpratyush** [coala/coala#4707]
Here is the output from `coala --ci` command - 
```
$ coala -v && coala --ci
0.11.0
[WARNING][04:36:26] Implicit 'Default' section inheritance is deprecated. It will be removed soon. To silence this warning remove settings in the 'Default' section from your coafile. You can use dots to specify inheritance: the section 'all.python' will inherit all settings from 'all'.
[ERROR][04:36:26] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][04:36:26] Exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/coalib/coala_main.py", line 81, in run_coala
    arg_list=arg_list)
  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/ConfigurationGathering.py", line 387, in gather_configuration
    log_printer)
  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/SectionFilling.py", line 31, in fill_settings
    bear_dirs = section.bear_dirs()
  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/Section.py", line 116, in bear_dirs
    for bear_dir in collect_registered_bears_dirs('coalabears')]
  File "/usr/local/lib/python3.4/dist-packages/coalib/collecting/Collectors.py", line 307, in collect_registered_bears_dirs
    registered_package = ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2087, in load
    if require: self.require(env, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2100, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'coala ~=0.11.0', 'at', ' ~=0.11.0')
The command "coala -v && coala --ci" exited with 255.
```
<br/>
Links:  

- [Coalafile](https://github.com/iiitv/algos/blob/master/.coafile)
- [Pull Request](https://github.com/iiitv/algos/pull/463/)
- [Build log](https://travis-ci.org/iiitv/algos/builds/273165947)
- [Travis Config](https://github.com/iiitv/algos/blob/master/.travis.yml)

**Comment by singhpratyush** [comment]
Seems to be resolved somehow.
