### ISSUE TITLE
cannot install on ubuntu14.04 ?

### ISSUE THREAD

**Issue by vTNT** [coala/coala#4716]
my os verison is ubuntu 14.04 run on docker 17.05
when i run: pip3 install coala-bears

it will have error:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'coala ~=0.11.0', 'at', ' ~=0.11.0')

Storing debug log for failure in /root/.pip/pip.log

**Comment by Makman2** [comment]
Do you have the old pip v1.x? You have to upgrade then ;)

**Comment by prakashdanish** [comment]
Try creating a new virtualenv, check 'Installation Errors' from the [Installation guide](http://docs.coala.io/en/latest/Users/Install.html)

**Comment by vTNT** [comment]
@prakashdanish  virtuallenv  it can work   thanku
