### ISSUE TITLE
Unable to collect Bear from X - Bear package names clash with bear's dependency module name

### ISSUE THREAD

**Issue by refeed** [coala/coala#4724]
Related to https://github.com/coala/coala/issues/2053

https://travis-ci.org/coala/coala-bears/jobs/276993965#L3832
```
The command "bash .ci/tests.sh" exited with 0.
1.95s$ .ci/generate_bear_requirements.py
WARNING:root:Unable to collect bears from /home/travis/build/coala/coala-bears/bears/general/LinkBackupBear.py. Probably the file is malformed or the module code raises an exception.
INFO:root:Exception was:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/coalib/collecting/Collectors.py", line 134, in icollect_bears
    for bear in _import_bears(matching_file, kinds):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/coalib/collecting/Collectors.py", line 26, in _import_bears
    types=list):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/coala_utils/decorators.py", line 26, in yield_once_generator
    for item in iterator(*args, **kwargs):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)
  File "/home/travis/build/coala/coala-bears/bears/general/LinkBackupBear.py", line 9, in <module>
    import tubeup.__main__
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/tubeup/__main__.py", line 30, in <module>
    import internetarchive.cli
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/internetarchive/cli/__init__.py", line 27, in <module>
    from internetarchive.cli import ia, ia_configure, ia_delete, ia_download, ia_list, \
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/internetarchive/cli/ia_metadata.py", line 50, in <module>
    from backports import csv
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/backports/csv.py", line 22, in <module>
    from csv import (
ImportError: cannot import name 'QUOTE_MINIMAL'
DEBUG:pip.vcs:Registered VCS backend: git
DEBUG:pip.vcs:Registered VCS backend: hg
DEBUG:pip.vcs:Registered VCS backend: svn
DEBUG:pip.vcs:Registered VCS backend: bzr
```

This is what `sys.path` contains when `.ci/generate_bear_requirements.py` runs:
```py
['./bears/general', './bears/elm', './bears/documentation', './bears/dart', './bears/csv', './bears/css', './bears/configfiles', './bears/coffee_script', './bears/cmake', './bears/c_languages/codeclone_detection', './bears/c_languages', './bears/apertium', './bears', '/home/rafid/GitHub/coala-bears', '/home/rafid/.venvs/coala-bears-py3/lib64/python36.zip', '/home/rafid/.venvs/coala-bears-py3/lib64/python3.6', '/home/rafid/.venvs/coala-bears-py3/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6', '/usr/lib/python3.6', '/home/rafid/.venvs/coala-bears-py3/lib/python3.6/site-packages', '/home/rafid/GitHub/coala-bears']
```

This happens because `sys.path` contains path to coala-bears packages, therefore the name of bear's dependency clash with package names in bears directory, such as `./bears/csv`.

When `Collectors` imports another bears, `coalib/collecting/Importers.py:_import_module()` appends bear's module path to `sys.path`, so when I run Travis-CI test for LinkBackupBear (https://github.com/coala/coala-bears/pull/1899) that one of the dependencies depends on `backports.csv`. When `backports.csv` imports the `csv` module, it imports the wrong `csv` module, it imports `./bears/csv` instead of the `csv` that `backports.csv` expects.

**Comment by KVGarg** [comment]
Hi, @refeed Are you still looking over this issue?

**Comment by refeed** [comment]
@KVGarg Hi, I've been inactive on this issue for a long time, so.. I think I'm not. Btw, feel free if you want to take over this issue

**Comment by KVGarg** [comment]
How to reproduce this error? I would like to give it a try!
