### ISSUE TITLE
Test compatibility on *BSDs

### ISSUE THREAD

**Issue by yukiisbored** [coala/coala#4736]
coala currently mainly tested and known to run on Linux, macOS, and Windows. It would be a good idea to test it on *BSDs (OpenBSD, FreeBSD, NetBSD, DragonFlyBSD, etc) as well to make sure coala is compatible with them.

List of known working BSDs:
- [ ] OpenBSD
- [ ] FreeBSD
- [ ] NetBSD
- [ ] DragonFlyBSD ( most likely will work if it works on FreeBSD )

**Comment by yukiisbored** [comment]
Testing it on OpenBSD.

Currently hitting a road block on coala-utils: https://gitlab.com/coala/coala-utils/issues/45

**Comment by krytarowski** [comment]
I can try NetBSD/amd64.

**Comment by krytarowski** [comment]
I've packaged coala in pkgsrc / NetBSD, but I'm annoyed by the strict dependencies on libraries. I'm having different versions of libraries, e.g. `libclang-py3`: `3.4.0` vs `3.9.0`.

I stopped on:

`pkg_resources.DistributionNotFound: The 'termcolor~=1.1.0' distribution was not found and is required by PyPrint`

```
$ pkg_info |grep termcolor                                                                                                                                                           
py36-termcolor-1.1.0 ANSII Color formatting for output in terminal
```

At least it builds including all the dependencies.

**Comment by krytarowski** [comment]
http://pkgsrc.se/wip/py-coala feel free to finish the package where I left it, once done I can import it to pkgsrc.

**Comment by krytarowski** [comment]
I had to use this patch locally:

```
$NetBSD$

--- setup.py.orig	2017-05-22 13:43:12.000000000 +0000
+++ setup.py
@@ -19,7 +19,7 @@ try:
     pf = platform.system()
     if pf != 'Windows' and lc == (None, None):
         locale.setlocale(locale.LC_ALL, 'C.UTF-8')
-except (ValueError, UnicodeError):
+except:
     locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
 
 
```

**Comment by yukiisbored** [comment]
@krytarowski Can you try it without packaging it? Try installing it with pip, we recommend doing it inside a virtualenv so it doesn't break your sites-package.

**Comment by yukiisbored** [comment]
Also, thanks for trying out packaging it on pkgsrc.

**Comment by yukiisbored** [comment]
I'll investigate the setup.py issue once I get a NetBSD VM up and running~

**Comment by krytarowski** [comment]
```
chieftec$ virtualenv-3.6 env                                                                                                                                                                 
Using base prefix '/usr/pkg'
New python executable in /tmp/test2/env/bin/python3.6
Also creating executable in /tmp/test2/env/bin/python
Installing setuptools, pip, wheel...done.
chieftec$ ls env
bin                include            lib                pip-selfcheck.json
chieftec$ ./env/                                                                                                                                                                             
bin/                 include/             lib/                 pip-selfcheck.json   
chieftec$ ./env/bin/p                                                                                                                                                                        
pip            pip3           pip3.6         python         python-config  python3        python3.6      
chieftec$ ./env/bin/pip3                                                                                                                                                                     
pip3    pip3.6  
chieftec$ ./env/bin/pip3.6 install coala                                                                                                                                                     
Collecting coala
  Downloading coala-0.11.0-py34.py35.py36-none-any.whl (190kB)
    100% |████████████████████████████████| 194kB 899kB/s 
Collecting appdirs~=1.4 (from coala)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting dependency-management~=0.4.0 (from coala)
  Downloading dependency_management-0.4.0-py3-none-any.whl
Collecting PyPrint~=0.2.6 (from coala)
  Downloading PyPrint-0.2.6-py3-none-any.whl
Collecting libclang-py3~=3.4.0 (from coala)
  Downloading libclang-py3-3.4.0.tar.gz
Requirement already satisfied: setuptools>=17.0 in ./env/lib/python3.6/site-packages (from coala)
Collecting requests~=2.12 (from coala)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 1.1MB/s 
Collecting Pygments~=2.1 (from coala)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 819kB/s 
Collecting colorlog~=2.7 (from coala)
  Downloading colorlog-2.10.0-py2.py3-none-any.whl
Collecting unidiff~=0.5.2 (from coala)
  Downloading unidiff-0.5.4-1-py2.py3-none-any.whl
Collecting coala-utils~=0.6.2 (from coala)
  Downloading coala_utils-0.6.6-py3-none-any.whl
Collecting sarge~=0.1.4 (from dependency-management~=0.4.0->coala)
  Downloading sarge-0.1.4.tar.gz (50kB)
    100% |████████████████████████████████| 51kB 1.7MB/s 
Collecting colorama~=0.3.7 (from PyPrint~=0.2.6->coala)
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting termcolor~=1.1.0 (from PyPrint~=0.2.6->coala)
  Using cached termcolor-1.1.0.tar.gz
Collecting certifi>=2017.4.17 (from requests~=2.12->coala)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 1.1MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests~=2.12->coala)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.6MB/s 
Collecting idna<2.7,>=2.5 (from requests~=2.12->coala)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 197kB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests~=2.12->coala)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 1.2MB/s 
Collecting pyreadline~=2.1 (from coala-utils~=0.6.2->coala)
  Downloading pyreadline-2.1.zip (109kB)
    100% |████████████████████████████████| 112kB 1.4MB/s 
Building wheels for collected packages: libclang-py3, sarge, termcolor, pyreadline
  Running setup.py bdist_wheel for libclang-py3 ... done
  Stored in directory: /home/kamil/.cache/pip/wheels/c5/60/d4/ea109e58092d55b8075ad0bce7772fed1eb259738c83f386d6
  Running setup.py bdist_wheel for sarge ... done
  Stored in directory: /home/kamil/.cache/pip/wheels/c8/19/6f/714ffb0829877dedfcaecad1ce3ce9f47fac1fbc5003345604
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: /home/kamil/.cache/pip/wheels/de/f7/bf/1bcac7bf30549e6a4957382e2ecab04c88e513117207067b03
  Running setup.py bdist_wheel for pyreadline ... done
  Stored in directory: /home/kamil/.cache/pip/wheels/9a/c7/45/fd424eb3d7875d7a61221accd593e17c7953ed5ece5ee60be9
Successfully built libclang-py3 sarge termcolor pyreadline
Installing collected packages: appdirs, sarge, colorama, termcolor, PyPrint, pyreadline, coala-utils, dependency-management, libclang-py3, certifi, chardet, idna, urllib3, requests, Pygments, colorlog, unidiff, coala
Successfully installed PyPrint-0.2.6 Pygments-2.2.0 appdirs-1.4.3 certifi-2017.7.27.1 chardet-3.0.4 coala-0.11.0 coala-utils-0.6.6 colorama-0.3.9 colorlog-2.10.0 dependency-management-0.4.0 idna-2.6 libclang-py3-3.4.0 pyreadline-2.1 requests-2.18.4 sarge-0.1.4 termcolor-1.1.0 unidiff-0.5.4 urllib3-1.22
chieftec$ find . -name coala
./env/bin/coala
chieftec$ ./env/bin/coala
[ERROR][04:12:10] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][04:12:10] Exception was:
Traceback (most recent call last):

  File "/tmp/test2/env/lib/python3.6/site-packages/coalib/coala.py", line 35, in main
    from coalib.output.ConsoleInteraction import (

  File "/tmp/test2/env/lib/python3.6/site-packages/coalib/output/ConsoleInteraction.py", line 8, in <module>
    import readline  # pylint: disable=unused-import

  File "/tmp/test2/env/lib/python3.6/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline

  File "/tmp/test2/env/lib/python3.6/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console

  File "/tmp/test2/env/lib/python3.6/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText

  File "/tmp/test2/env/lib/python3.6/site-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes

  File "/usr/pkg/lib/python3.6/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):

ValueError: _type_ 'v' not supported
```

**Comment by yukiisbored** [comment]
Yeah, we seriously should fix coala_utils. It shouldn't download pyreadline on anything other than Windows.

**Comment by yukiisbored** [comment]
Thanks a lot!

**Comment by krytarowski** [comment]
Once it will work and be packageable, I will be happy to push it from pkgsrc wip (work-in-progress) to pkgsrc.

**Comment by yukiisbored** [comment]
Just tested it on FreeBSD 12.0-CURRENT, everything works normally. but I think there's some issue with sqlite3 on Python 3.6

```
± coala                  
[WARNING][19:49:23] Unable to collect bears from /usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/bears/vcs/git/GitCommitBear.py. Probably the file is malformed or the module code raises an exception.
[INFO][19:49:23] Exception was:
Traceback (most recent call last):

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/coalib/collecting/Collectors.py", line 129, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/coalib/collecting/Collectors.py", line 27, in _import_bears
    types=list):

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/coala_utils/decorators.py", line 26, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/bears/vcs/git/GitCommitBear.py", line 1, in <module>
    import nltk

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/nltk/__init__.py", line 137, in <module>
    from nltk.stem import *

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/nltk/stem/__init__.py", line 29, in <module>
    from nltk.stem.snowball import SnowballStemmer

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/nltk/stem/snowball.py", line 32, in <module>
    from nltk.corpus import stopwords

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/nltk/corpus/__init__.py", line 66, in <module>
    from nltk.corpus.reader import *

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/nltk/corpus/reader/__init__.py", line 105, in <module>
    from nltk.corpus.reader.panlex_lite import *

  File "/usr/home/yuki/.virtualenvs/moe/lib/python3.6/site-packages/nltk/corpus/reader/panlex_lite.py", line 15, in <module>
    import sqlite3

  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *

  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *

ModuleNotFoundError: No module named '_sqlite3'
[WARNING][19:49:23] No bears matching 'GitCommitBear' were found. Make sure you have coala-bears installed or you have typed the name correctly.
Executing section all...
Executing section all.python.analysis...
Executing section all.python.spacing...
Executing section all.commit...
Executing section cli...
```

**Comment by yukiisbored** [comment]
Ah, sqlite bindings doesn't ship with py3.6 (classic FreeBSD)
```
± doas pkg install py36-sqlite3 
Password:
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: gstreamer1-plugins-lame has a missing dependency: lame
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py36-sqlite3: 3.6.3_7

Number of packages to be installed: 1

28 KiB to be downloaded.

Proceed with this action? [y/N]: y
[1/1] Fetching py36-sqlite3-3.6.3_7.txz: 100%   28 KiB  28.7kB/s    00:01    
Checking integrity... done (0 conflicting)
[1/1] Installing py36-sqlite3-3.6.3_7...
Extracting py36-sqlite3-3.6.3_7: 100%
± coala
Executing section all...
Executing section all.python.analysis...
Executing section all.python.spacing...
Executing section all.commit...
[nltk_data] Downloading package punkt to /home/yuki/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package maxent_treebank_pos_tagger to
[nltk_data]     /home/yuki/nltk_data...
[nltk_data]   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/yuki/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
Executing section cli...
```

**Comment by jayvdb** [comment]
@krytarowski wrt https://github.com/coala/coala/issues/4736#issuecomment-334978044 , could you tell us which exception is raised?

**Comment by jayvdb** [comment]
@yukiisbored , would it be a good idea to get nltk data packages onto BSDs?  They are very rarely updated.

**Comment by yukiisbored** [comment]
@jayvdb Not sure, just try packaging it and send it to the mailing list.

**Comment by krytarowski** [comment]
> @krytarowski wrt #4736 (comment) , could you tell us which exception is raised?

Not really, I'm not into Python.

**Comment by yukiisbored** [comment]
Personally, I can confirm that OpenBSD, FreeBSD, and DragonflyBSD works. Just need to test on NetBSD.
