### ISSUE TITLE
master fails on Fedora 26

### ISSUE THREAD

**Issue by SanketDG** [coala/coala#4881]
Fresh install of `coala` and `coala-bears` master on a new venv:

```
[WARNING][11:33:59] Implicit 'Default' section inheritance is deprecated. It will be removed soon. To silence this warning remove settings in the 'Default' section from your coafile. You can use dots to specify inheritance: the section 'all.python' will inherit all settings from 'all'.
[ERROR][11:34:02] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][11:34:02] Exception was:
Traceback (most recent call last):

  File "/home/sanketdg/projects/coala/coalib/coala.py", line 84, in main
    args)

  File "/home/sanketdg/projects/coala/coalib/output/ConsoleInteraction.py", line 990, in show_bears
    print_bears(bears, show_description, show_params, console_printer, args)

  File "/home/sanketdg/projects/coala/coalib/output/ConsoleInteraction.py", line 950, in print_bears
    separators=(',', ': '))

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 438, in _iterencode
    yield from _iterencode(o, _current_indent_level)

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 438, in _iterencode
    yield from _iterencode(o, _current_indent_level)

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 428, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks

  File "/home/sanketdg/.pyenv/versions/3.6.1/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)

  File "/home/sanketdg/projects/coala/coalib/output/JSONEncoder.py", line 32, in default
    for member in get_public_members(obj)}

  File "/home/sanketdg/.pyenv/versions/3.6.1/envs/coala/lib/python3.6/site-packages/coala_utils/decorators.py", line 134, in get_public_members
    return {attr: getattr(obj, attr) for attr in dir(obj)

  File "/home/sanketdg/.pyenv/versions/3.6.1/envs/coala/lib/python3.6/site-packages/coala_utils/decorators.py", line 136, in <dictcomp>
    and not hasattr(getattr(obj, attr), '__call__')}

  File "/home/sanketdg/.pyenv/versions/3.6.1/envs/coala/lib/python3.6/site-packages/dependency_management/requirements/DistributionRequirement.py", line 205, in package_managers
    self.get_package_managers())

  File "/home/sanketdg/.pyenv/versions/3.6.1/envs/coala/lib/python3.6/site-packages/dependency_management/requirements/DistributionRequirement.py", line 193, in get_package_managers
    '{}'.format(','.join(self.packages.keys())))

NotImplementedError: This platform doesn't have any of the specified package manager(s): apt_get
```

**Comment by Makman2** [comment]
Which OS are you running on? Seems for me we haven't adapted some requirement for your platform^^

**Comment by SanketDG** [comment]
Fedora 26, previously used yum (till 21 iirc), now uses dnf

**Comment by Makman2** [comment]
Confirmed, I get the same ;)

**Comment by Makman2** [comment]
CC @shreyans800755 , as it is caused by the `--show-bears` and `--json` options :+1:

**Comment by shreyans800755** [comment]
@Makman2 @SanketDG 
I'm getting all the bears in json format as expected. I'm on ubuntu 16.04 system. Can this be specific to your system ?

**Comment by SanketDG** [comment]
Yeah, probably, but I cant seem to find where exactly is `DistributionRequirement` used....

**Comment by shreyans800755** [comment]
I've created a PR to test this scenario on CI at https://github.com/coala/coala/pull/4913.
It looks like it is giving the same error as you are getting but with different package manager - `brew`.

Ref https://travis-ci.org/coala/coala/jobs/307175601#L1659
Same error is there on Circle as well.

**Comment by newbazz** [comment]
I would like to work on this issue.

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by anctartica** [comment]
I would like to fix this. @newbazz are you still working on this?

**Comment by newbazz** [comment]
yes you can take the issue.

**Comment by anctartica** [comment]
So far while exploring the traceback I have figured out that the issue is caused by 'package_managers' attribute of the object. When you call getattr(obj, 'package_managers') it is actually checking whether the package is installed or not and therefore failing.

**Comment by Makman2** [comment]
All that are necessary ;)

**Comment by anctartica** [comment]
since I am unable to run this command locally, what is the expected output for `coala -B --json`? Do i get a list of the names of bears in json or do I also get other information about them such as this ?

> "ASCIINEMA_URL": "https://asciinema.org/a/89021",
      "AUTHORS": [
        "The coala developers"
      ],
      "AUTHORS_EMAILS": [
        "coala-devel@googlegroups.com"
      ],
      "BEAR_DEPS": [],
      "CAN_DETECT": [],
      "CAN_FIX": [
        "Formatting"
      ],
      "INCLUDE_LOCAL_FILES": [],
      "LANGUAGES": [
        "Python 3",
        "Python 2",
        "Python"
      ],
      "LICENSE": "AGPL-3.0",
      "MAINTAINERS": [],
      "MAINTAINERS_EMAILS": [],
      "PLATFORMS": [
        "any"
      ],

**Comment by anctartica** [comment]
What is the correct output for this command? Do you get the list of bears in JSON format or do also get some other information such as this:

> "ASCIINEMA_URL": "https://asciinema.org/a/89021",
      "AUTHORS": [
        "The coala developers"
      ],
      "AUTHORS_EMAILS": [
        "coala-devel@googlegroups.com"
      ],
      "BEAR_DEPS": [],
      "CAN_DETECT": [],
      "CAN_FIX": [
        "Formatting"
      ],
      "INCLUDE_LOCAL_FILES": [],
      "LANGUAGES": [
        "Python 3",
        "Python",
        "Python 2"
      ],
      "LICENSE": "AGPL-3.0",
      "MAINTAINERS": [],
      "MAINTAINERS_EMAILS": [],
      "PLATFORMS": [
        "any"

**Comment by Makman2** [comment]
Good question. `--json` usually means that someone wants more, computer-readable / -serializable information, but without `--json` only the bear names are displayed. @anctartica up to you to decide the correct behaviour, but in my opinion the extra info is good and useful if someone already uses `--json`.

**Comment by shreyans800755** [comment]
@Makman2 @anctartica 
`coala -B --json` works on my local. It is showing all the details and just names.

But the behaviour is inconsistent with `coala -B` which only shows the names of the bears and not the details.
Content wise, output of `coala -B --json` matches with the output of `coala -B --show-details`.

To keep the consistency, we should only display the names of the bears unless details are asked using other args. However, I think it is outside of the scope of this issue. So, I've created another issue for that at https://github.com/coala/coala/issues/5156.
@Makman2 Can you block the new issue on this one and mark it as bug as well ?

**Comment by Makman2** [comment]
But I think that one is not really a bug, rather an enhancement or "feature".

**Comment by anctartica** [comment]
If I have to update files in `coala_utils` to fix this issue then would this issue have to be closed here and opened in the `coala_utils` repo which is on gitlab?

**Comment by Makman2** [comment]
Why `coala-utils`? This shouldn't require changes there
