### ISSUE TITLE
Unable to run code analysis

### ISSUE THREAD

**Issue by maliknaik16** [coala/coala#5174]
### Overview Description
Running ```SpaceConsistencyBear``` on c program from the getting started with coala([Github](https://github.com/coala/coala-tutorial/blob/master/src/main.c)) using the following command:
```coala --files=main.c --bears=SpaceConsistencyBear --save```

# Steps to Reproduce

1. Install python 3.4.4 on Windows 8.1
2. ```pip3 install coala-bears```
3. ```pip3 install virtualenv```
4. Create a simple program with the following code and save it as main.c
```
#include <stdio.h> 

int main(void) {
    printf("Welcome to coala. Keep following the tutorial, you are doing a great job so far!\n");

    return 0;
}

````
6. run virtualenv from ```[python34 instaled directory]\Lib\venv\scripts\nt\activate.bat``` and go to the location where your main.c file is located.
5. run the command ```coala --files=main.c --bears=SpaceConsistencyBear --save```

# Actual Results
```
←[31m[ERROR]←[0m[21:29:30] An unknown error occurred. This is a bug. We are sorr
y for the inconvenience. Please contact the developers for assistance. During ex
ecution of coala an exception was raised. This should never happen. When asked f
or, the following information may help investigating:←[0m
←[34m[INFO]←[0m[21:29:30] Exception was:
Traceback (most recent call last):

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2801, in
_dep_map
    return self.__dep_map

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2658, in
__getattr__
    raise AttributeError(attr)

AttributeError: _DistInfoDistribution__dep_map


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\python34\lib\site-packages\coalib\coala_main.py", line 81, in run_coa
la
    arg_list=arg_list)

  File "c:\python34\lib\site-packages\coalib\settings\ConfigurationGathering.py"
, line 387, in gather_configuration
    log_printer)

  File "c:\python34\lib\site-packages\coalib\settings\SectionFilling.py", line 3
1, in fill_settings
    bear_dirs = section.bear_dirs()

  File "c:\python34\lib\site-packages\coalib\settings\Section.py", line 116, in
bear_dirs
    for bear_dir in collect_registered_bears_dirs('coalabears')]

  File "c:\python34\lib\site-packages\coalib\collecting\Collectors.py", line 307
, in collect_registered_bears_dirs
    registered_package = ep.load()

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2354, in
load
    self.require(*args, **kwargs)

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2371, in
require
    items = working_set.resolve(reqs, env, installer)

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 847, in r
esolve
    new_requirements = dist.requires(req.extras)[::-1]

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2602, in
requires
    dm = self._dep_map

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2803, in
_dep_map
    self.__dep_map = self._compute_dependencies()

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2836, in
_compute_dependencies
    common = frozenset(reqs_for_extra(None))

  File "c:\python34\lib\site-packages\pkg_resources\__init__.py", line 2833, in
reqs_for_extra
    if req.marker_fn(override={'extra':extra}):

  File "c:\python34\lib\site-packages\_markerlib\markers.py", line 113, in marke
r_fn
    return eval(compiled_marker, environment)

  File "<environment marker>", line 1, in <module>

NameError: name 'platform_system' is not defined←[0m

```
# Expected Results
Coala should ask me to remove trailing space. [From here](https://docs.coala.io/en/latest/Users/Tutorial.html)

# Additional Information:
Operating System: Windows 8.1 64-bit
Python Version: 3.4.4

**Comment by Makman2** [comment]
Which `setuptools` version are you using?

Please update `setuptools`, this should resolve the error (but please check the version before! not that our requirements from the latest stable have to be updated and we need a bugfix-backport).

**Comment by maliknaik16** [comment]
```setuptools``` version is 18.2

**Comment by maliknaik16** [comment]
@Makman2 - updating ```setuptools``` solved my problem. Thanks.

Also i think we need to add a note in the getting started page or in homepage to make sure to update the setuptools
```python -m pip install --upgrade pip setuptools wheel```
