### ISSUE TITLE
coala -B --json fails when one bear fails

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5406]
`coala -B --json` (and probably just `coala -B`) return a non-exit code when one of the bears can not be loaded.  It should show which bears can not be loaded.

```
 coala -B --json
[WARNING][02:46:37] Implicit 'Default' section inheritance is deprecated. It will be removed soon. To silence this warning remove settings in the 'Default' section from your coafile. You can use dots to specify inheritance: the section 'all.python' will inherit all settings from 'all'.
[WARNING][02:46:37] Unable to collect bears from /home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/bears/c_languages/ClangBear.py. Probably the file is malformed or the module code raises an exception.
[INFO][02:46:37] Exception was:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/coalib/collecting/Collectors.py", line 134, in icollect_bears
    for bear in _import_bears(matching_file, kinds):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/coalib/collecting/Collectors.py", line 26, in _import_bears
    types=list):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/coala_utils/decorators.py", line 27, in yield_once_generator
    for item in iterator(*args, **kwargs):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/bears/c_languages/ClangBear.py", line 1, in <module>
    from clang.cindex import Index, LibclangError
ImportError: No module named 'clang'
```

https://travis-ci.org/coala/coala/jobs/368944378

**Comment by shashwatmishra76** [comment]
@jayvdb coala -B does list out all the bears but coala -B --json seems to throw errors.So this command i.e. coala -B --json should give out the list of all bears in json format even if some bears can't be loaded,right?

**Comment by shashwatmishra76** [comment]
I am asking this because coala -B works just fine as it lists out all the bears and does not shut down even if some of the beards are missing.I don't think I need to make changes regarding the command coala -B,right?
