### ISSUE TITLE
Ignore Bears that start with an _

### ISSUE THREAD

**Issue by virresh** [coala/coala#5476]
coala should ignore bears that start with an _ , since these are not meant to be exposed to the user

e.g, the the _CommitBear is not meant to be exposed directly, it should only be inherited by a VCS Bear and then become invokable

currently if we do 
```
 $ coala -B | grep Commit
[INFO][13:51:23] Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
[INFO][13:51:23] Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
_CommitBear
GitCommitBear
HgCommitBear
```
The _CommitBear should not be exposed.

Also note that the file in which `CommitBear` is defined is not exactly `_CommitBear`, due to which a user cannot use `bears=_CommitBear` inside the .coafile
But if the user writes `bears=CommitBear`, then the `_CommitBear` is invoked.

Here's a sample output of the debug logs when one runs _CommitBear by specifying `bears = CommitBear` in the `.coafile`:

```
[DEBUG][13:47:42] Running bear _CommitBear...
[ERROR][13:47:42] Bear _CommitBear failed to run. Take a look at debug messages (`-V`) for further information.
[DEBUG][13:47:42] The bear _CommitBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/mnt/Common/Earlier/GIT/coala/coala/coalib/bears/Bear.py", line 309, in execute
    return [] if result is None else list(result)
  File "/mnt/Common/Earlier/GIT/coala/coala-bears/bears/vcs/CommitBear.py", line 136, in run
    (stdout, stderr) = self.get_head_commit()
TypeError: 'NoneType' object is not iterable
```

**Comment by jayvdb** [comment]
It is critical to note that `_CommitBear` is not a dependency bear -- it is abstract ... it exists only to hold common methods, and the abstract methods must be implemented for the bear to be .. not abstract.

**Comment by Makman2** [comment]
What I have problems with is that a `_` preceding a name is already common convention and means usually that it's "private", so nobody outside that python file shall access it (there are only very rare exceptions, like `namedtuple` functions).

Can we somehow mark bears differently if they are abstract or a dependency and only intended for programming-use?
For example setting a field like we already do for metadata and some bear-behaviour properties. Or for abstract classes only, use the `abc` module facility in bear classes to detect abstractness of a class.
