### ISSUE TITLE
coala scans .bak files which it creates

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5479]
This is a bit odd

```py
[WARNING][08:45:26] Bear KeywordBear failed to run on file /home/travis/build/coala/community/.coafile.bak. Take a look at debug messages (`-V`) for further information.
[DEBUG][08:45:26] The bear KeywordBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.
Traceback information is provided below:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coalib/bears/Bear.py", line 282, in execute
    return [] if result is None else list(result)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bears/general/KeywordBear.py", line 97, in run
    comments = list(_get_comments(dependency_results))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bears/general/KeywordBear.py", line 23, in _get_comments
    if isinstance(result.contents, str):
AttributeError: 'Result' object has no attribute 'contents'
```

https://github.com/coala/community/pull/106#issuecomment-383366137

The [Travis build](https://github.com/coala/community/blob/master/.travis.yml) script doesnt do anything unusual, such as caching the previous coala run data, yet somehow coala is finding and linting a `.coafile.bak` and running into trouble with it.

**Comment by Makman2** [comment]
When is `.coafile.bak` created? During the same run or in a previous one?

**Comment by jayvdb** [comment]
And I've confirmed there are no .bak files prior to `coala-ci` being run
https://travis-ci.org/jayvdb/community/jobs/391308269#L868

**Comment by jayvdb** [comment]
Ah, but a .bak is created before the coala-ci run, only for PRs.
see https://github.com/coala/community/pull/106#issuecomment-397858154

And I guess this is exposing some other bug, as it is only appearing in that PR and not others.  `.coafile` is being modified, and maybe that is why it is finding `.coafile.bak`.

**Comment by anctartica** [comment]
This verifies that there is `.coafile.bak` during the run of `coala` as well. 
https://travis-ci.org/anctartica/coala/jobs/393644659

**Comment by anctartica** [comment]
This verifies that coala isn't linting the `.coafile.bak` that is created in the main `coala` repo:
https://travis-ci.org/anctartica/coala/jobs/393651709
