### ISSUE TITLE
pytest failing on all CI

### ISSUE THREAD

**Issue by MacBox7** [coala/coala#5539]
The error is =>
```
#!/bin/bash -eo pipefail
python -m pytest

Traceback (most recent call last):
  File "/home/circleci/.local/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2321, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2344, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 3.1.3 (/home/circleci/.local/lib/python3.4/site-packages), Requirement.parse('pytest>=3.6.0'))
```

Probably some dependency made usage of higher `pytest` version mandatory. The change needs to be made in coala-mobans. So that it can be resolved in all repos.

**Comment by jayvdb** [comment]
Also very related is the next part of the log

```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  ...
  File "/home/circleci/.local/lib/python3.4/site-packages/_pytest/config.py", line 934, in pytest_cmdline_parse
    self.parse(args)
  File "/home/circleci/.local/lib/python3.4/site-packages/_pytest/config.py", line 1106, in parse
    self._preparse(args, addopts=addopts)
  File "/home/circleci/.local/lib/python3.4/site-packages/_pytest/config.py", line 1068, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/home/circleci/.local/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 515, in load_setuptools_entrypoints
    "Plugin %r could not be loaded: %s!" % (ep.name, e))
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'timeout' could not be loaded: (pytest 3.1.3 (/home/circleci/.local/lib/python3.4/site-packages), Requirement.parse('pytest>=3.6.0'))!
Exited with code 1
```

As it is timeout plugin, it is related to https://github.com/coala/coala/issues/5525

**Comment by jayvdb** [comment]
It is the same problem ... https://github.com/coala/coala/commits/0257f4ac3a44ce988975c9cd0fb81c0743c989c3 hasnt been rebased in 28 days :P

**Comment by MacBox7** [comment]
Yes the error is due to pytest-timeout and the reason I am facing the problem is because `mobans` has not been updated with  [this](https://github.com/coala/coala/pull/5526/files) patch. checkout [test-requirements.txt.jj2](https://gitlab.com/coala/mobans/blob/master/templates/test-requirements.txt.jj2).

I strongly feel that the moban check using  should be integrated to CI so that such inconsistencies don't occur.
By check I mean
```
moban
git diff --exit-code
```

**Comment by jayvdb** [comment]
Check your assumptions.  See https://gitlab.com/coala/mobans/merge_requests/32

**Comment by jayvdb** [comment]
@macbox7, update?

**Comment by MacBox7** [comment]
My fault totally. Had 2 instances of test-requirements.txt.jj2. Hence older one was overriding the other. Sorry for the inconvenience.
