### ISSUE TITLE
pyyaml fails on Python 3.7-dev

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5559]
Build error

https://travis-ci.org/jayvdb/coala/jobs/395717595

**Comment by jayvdb** [comment]
This is likely fixed by using the just released PyYAML 4.1.x

**Comment by jayvdb** [comment]
The cause is actually moban, as it requires pyyaml.  coala core does not.

But coala-bears does require PyYAML 3.12, so we have a version problem.

**Comment by jayvdb** [comment]
vint pins the pyyaml version.

https://travis-ci.org/jayvdb/vint/builds/397900637

**Comment by jayvdb** [comment]
See https://github.com/Kuniwak/vint/issues/279

**Comment by jayvdb** [comment]
Still a problem
https://travis-ci.org/coala/coala/jobs/398686523

**Comment by jayvdb** [comment]
Note pyyaml 4.1 was released and did fix our problems, but had significant other issue and so they removed it from pypi, causing a new slew of issues.

**Comment by joncasdam** [comment]
any plans on releasing a fix for this issue?
because it's still going around...  :/

```
coala==0.11.0
coala-bears==0.11.1
coala-utils==0.6.7
```

here's the traceback
```
Traceback (most recent call last):
  File "/data-venvs/.coalavenv/lib/python3.6/site-packages/coalib/coala_main.py", line 81, in run_coala
    arg_list=arg_list)
  File "/data-venvs/.coalavenv/lib/python3.6/site-packages/coalib/settings/ConfigurationGathering.py", line 387, in gather_configuration
    log_printer)
  File "/data-venvs/.coalavenv/lib/python3.6/site-packages/coalib/settings/SectionFilling.py", line 31, in fill_settings
    bear_dirs = section.bear_dirs()
  File "/data-venvs/.coalavenv/lib/python3.6/site-packages/coalib/settings/Section.py", line 116, in bear_dirs
    for bear_dir in collect_registered_bears_dirs('coalabears')]
  File "/data-venvs/.coalavenv/lib/python3.6/site-packages/coalib/collecting/Collectors.py", line 307, in collect_registered_bears_dirs
    registered_package = ep.load()
  File "/data-venvs/.coalavenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/data-venvs/.coalavenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/data-venvs/.coalavenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyYAML 4.2b1 (/data-venvs/.coalavenv/lib/python3.6/site-packages), Requirement.parse('pyyaml~=3.12'))
```
