### ISSUE TITLE
AppVeyor failure: PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5571]
https://ci.appveyor.com/project/coala/coala/build/1.0.13331/job/7stk9roj690frdq6

```py
tests\coalaTest.py ......
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
~~~~~~~~~~~~~~~~~~~~~~~~~~ Stack of MainThread (552) ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\py.test.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\python34\lib\site-packages\_pytest\config\__init__.py", line 65, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python34\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python34\lib\site-packages\_pytest\main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python34\lib\site-packages\_pytest\main.py", line 178, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\python34\lib\site-packages\_pytest\main.py", line 215, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python34\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python34\lib\site-packages\_pytest\main.py", line 236, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python34\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python34\lib\site-packages\_pytest\runner.py", line 64, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\python34\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "c:\python34\lib\site-packages\_pytest\runner.py", line 159, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\python34\lib\site-packages\_pytest\runner.py", line 183, in call_runtest_hook
    treat_keyboard_interrupt_as_exception=item.config.getvalue("usepdb"),
  File "c:\python34\lib\site-packages\_pytest\runner.py", line 198, in __init__
    self.result = func()
  File "c:\python34\lib\site-packages\_pytest\runner.py", line 181, in <lambda>
    lambda: ihook(item=item, **kwds),
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python34\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python34\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python34\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "c:\python34\lib\site-packages\_pytest\unittest.py", line 186, in runtest
    self._testcase(result=self)
  File "c:\python34\lib\unittest\case.py", line 628, in __call__
    return self.run(*args, **kwds)
  File "c:\python34\lib\unittest\case.py", line 580, in run
    testMethod()
  File "C:\projects\coala\tests\coalaTest.py", line 303, in test_coala_with_color
    coala.main, 'coala')
  File "C:\projects\coala\tests\TestUtilities.py", line 44, in execute_coala
    retval = func(debug=debug)
  File "C:\projects\coala\coalib\coala.py", line 120, in main
    return mode_normal(console_printer, None, args, debug=debug)
  File "C:\projects\coala\coalib\coala_modes.py", line 28, in mode_normal
    debug=debug)
  File "C:\projects\coala\coalib\coala_main.py", line 184, in run_coala
    False))
  File "C:\projects\coala\coalib\processes\Processing.py", line 790, in execute_section
    use_raw_files=use_raw_files)
  File "C:\projects\coala\coalib\processes\Processing.py", line 400, in instantiate_processes
    manager = processing.Manager()
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python34\lib\multiprocessing\spawn.py", line 100, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "c:\python34\lib\multiprocessing\reduction.py", line 86, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
Command exited with code 1
```

**Comment by jayvdb** [comment]
cc @Makman2

**Comment by jayvdb** [comment]
Probably unrelated, we had a transient error in `test_coala_with_color` on Linux at
https://circleci.com/gh/coala/coala/17936
A rebuild of the job fixed it.

**Comment by jayvdb** [comment]
https://ci.appveyor.com/project/coala/coala/build/1.0.13410/job/9gudc68m9b31jmvh
```
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
~~~~~~~~~~~~~~~~~~~~~~~~~~ Stack of MainThread (2088) ~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "c:\python34-x64\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34-x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34-x64\Scripts\py.test.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\python34-x64\lib\site-packages\_pytest\config\__init__.py", line 64, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python34-x64\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python34-x64\lib\site-packages\_pytest\main.py", line 208, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python34-x64\lib\site-packages\_pytest\main.py", line 178, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\python34-x64\lib\site-packages\_pytest\main.py", line 215, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python34-x64\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python34-x64\lib\site-packages\_pytest\main.py", line 236, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python34-x64\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python34-x64\lib\site-packages\_pytest\runner.py", line 64, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\python34-x64\lib\site-packages\_pytest\runner.py", line 79, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "c:\python34-x64\lib\site-packages\_pytest\runner.py", line 159, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\python34-x64\lib\site-packages\_pytest\runner.py", line 183, in call_runtest_hook
    treat_keyboard_interrupt_as_exception=item.config.getvalue("usepdb"),
  File "c:\python34-x64\lib\site-packages\_pytest\runner.py", line 199, in __init__
    self.result = func()
  File "c:\python34-x64\lib\site-packages\_pytest\runner.py", line 181, in <lambda>
    lambda: ihook(item=item, **kwds),
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python34-x64\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "c:\python34-x64\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "c:\python34-x64\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_call
    item.runtest()
  File "c:\python34-x64\lib\site-packages\_pytest\unittest.py", line 184, in runtest
    self._testcase(result=self)
  File "c:\python34-x64\lib\unittest\case.py", line 628, in __call__
    return self.run(*args, **kwds)
  File "c:\python34-x64\lib\unittest\case.py", line 580, in run
    testMethod()
  File "C:\projects\coala\tests\coalaTest.py", line 303, in test_coala_with_color
    coala.main, 'coala')
  File "C:\projects\coala\tests\TestUtilities.py", line 44, in execute_coala
    retval = func(debug=debug)
  File "C:\projects\coala\coalib\coala.py", line 120, in main
    return mode_normal(console_printer, None, args, debug=debug)
  File "C:\projects\coala\coalib\coala_modes.py", line 28, in mode_normal
    debug=debug)
  File "C:\projects\coala\coalib\coala_main.py", line 184, in run_coala
    False))
  File "C:\projects\coala\coalib\processes\Processing.py", line 813, in execute_section
    runner.start()
  File "c:\python34-x64\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\python34-x64\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\python34-x64\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "c:\python34-x64\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\python34-x64\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
~~~~~~~~~~~~~~~~~~~~~~ Stack of QueueFeederThread (1468) ~~~~~~~~~~~~~~~~~~~~~~~
  File "c:\python34-x64\lib\threading.py", line 879, in _bootstrap
    self._bootstrap_inner()
  File "c:\python34-x64\lib\threading.py", line 911, in _bootstrap_inner
    self.run()
  File "c:\python34-x64\lib\threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python34-x64\lib\multiprocessing\queues.py", line 249, in _feed
    send_bytes(obj)
  File "c:\python34-x64\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python34-x64\lib\multiprocessing\connection.py", line 284, in _send_bytes
    [ov.event], False, INFINITE)
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
Command exited with code 1
```
