### ISSUE TITLE
Listing bears failes with ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by feddischson** [coala/coala#5725]
### Overview Description
Listing bears failes with ImportError: attempted relative import with no known parent package

# Steps to Reproduce

1. pip3 install --user coala-bears
2. python3.6 ~/.local/lib64/python3.6/site-packages/coalib/coala.py -B

# Actual Results

```
[WARNING][09:32:28] Unable to collect bears from /home/christian/.local/lib64/python3.6/site-packages/coalib/bears/Bear.py. Probably the file is malformed or the module code raises an exception.
[INFO][09:32:28] Exception was:
Traceback (most recent call last):

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Collectors.py", line 129, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Collectors.py", line 27, in _import_bears
    types=list):

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)

  File "/home/christian/.local/lib64/python3.6/site-packages/coala_utils/decorators.py", line 26, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/bears/Bear.py", line 21, in <module>
    from .meta import bearclass

ImportError: attempted relative import with no known parent package
[WARNING][09:32:28] Unable to collect bears from /home/christian/.local/lib64/python3.6/site-packages/coalib/bears/Bear.py. Probably the file is malformed or the module code raises an exception.
[INFO][09:32:28] Exception was:
Traceback (most recent call last):

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Collectors.py", line 129, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Collectors.py", line 27, in _import_bears
    types=list):

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)

  File "/home/christian/.local/lib64/python3.6/site-packages/coala_utils/decorators.py", line 26, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)

  File "/home/christian/.local/lib64/python3.6/site-packages/coalib/bears/Bear.py", line 21, in <module>
    from .meta import bearclass

ImportError: attempted relative import with no known parent package
GlobalBear
LocalBear

```
# Expected Results
A list of bears.

# Reproducibility
Full

# Additional Information:
 - coalib version 0.11.0
 - coala_utils 0.6.7

**Comment by mach64** [comment]
All you need to do is run `coala -B` to get the expected results. You shouldn't be specifying the path to `coala.py` directly, which is what causes the import errors in your case.
