### ISSUE TITLE
Import Error while running coala tutorial

### ISSUE THREAD

**Issue by 2root2** [coala/coala#5791]
### Overview Description

I was running [coala tutorial](https://docs.coala.io/en/latest/Users/Tutorial.html)
getting following error.

```
[INFO][12:47:01] Exception was:
Traceback (most recent call last):

  File "/Users/mohan/ds_coala/cvenv/lib/python3.6/site-packages/coalib/collecting/Collectors.py", line 129, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/Users/mohan/ds_coala/cvenv/lib/python3.6/site-packages/coalib/collecting/Collectors.py", line 27, in _import_bears
    types=list):

  File "/Users/mohan/ds_coala/cvenv/lib/python3.6/site-packages/coalib/collecting/Importers.py", line 160, in iimport_objects
    attributes, local)

  File "/Users/mohan/ds_coala/cvenv/lib/python3.6/site-packages/coala_utils/decorators.py", line 26, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/Users/mohan/ds_coala/cvenv/lib/python3.6/site-packages/coalib/collecting/Importers.py", line 119, in _iimport_objects
    module = _import_module(file_path)

  File "/Users/mohan/ds_coala/cvenv/lib/python3.6/site-packages/coalib/collecting/Importers.py", line 31, in _import_module
    return __import__(module_name)

  File "/Users/mohan/ds_coala/coala-bears-master/bears/general/LineLengthBear.py", line 7, in <module>
    from coalib.settings.Setting import typed_list, language

ImportError: cannot import name 'language'
```

# Steps to Reproduce

1. Cloned ` https://github.com/2root2/coala-bears.git`
2. Installed repo contents using  `pip3 install -e .`
3. Clone coala tutorial `git clone https://github.com/coala/coala-tutorial`
4. run `coala -S Makefiles.bears=LineLengthBear Makefiles.files=Makefile --save`

# Actual Results
As mentioned in issue body

# Expected Results
coala runs correctly.
# Additional Information:
I'm running virtual environment with pip version `9.0.1` and Python `3.6`

**Comment by Wwar-lock** [comment]
Hello, @2root2 Once Try Python 3.7.0 and pip  10.0.1.

**Comment by RaiVaibhav** [comment]
Seems like version of coala is not updated can you try to install the latest version of coala, because it worked fine for me
```(colloquium) vaibhav@Vaibhav:~/coala-bears$ python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from coalib.settings.Setting import typed_list, language
>>> 
```

**Comment by KaustubhDamania** [comment]
Is this issue still open?

**Comment by mitchell-frost** [comment]
I am new to coala. Can I work on this?

**Comment by mitchell-frost** [comment]
I'll start working on it @abhishalya thanks!

**Comment by mitchell-frost** [comment]
I am not getting the error
![Screenshot (29)](https://user-images.githubusercontent.com/44670836/82823296-efab9700-9ec4-11ea-88d0-8f015dc710c2.png)

**Comment by mitchell-frost** [comment]
@2root2 I issued the command:
 pip3 install coala-bears 
after cloning the repo. Can you check and see?
