### ISSUE TITLE
Support pylint >= 2.0

### ISSUE THREAD

**Issue by StoppingBuck** [coala/coala#5871]
It seems the current version of coala-bears doesn't support the newest version of pylint, thus can't run on newer versions. 

On Arch Linux:

```
 ✘ mp@archoffice  ~/code  coala --files UPSERT_PAYMENTS_FROM_LEADR.csv --bears CSVLintBear
[WARNING][14:18:41] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any use of config files with `-I`.
[ERROR][14:18:41] There is a conflict in the version of a dependency you have installed and the requirements of coala. This may be resolved by creating a separate virtual environment for coala or running `pip install "pylint~=1.6"`. Be aware that the latter solution might break other python packages that depend on the currently installed version.
[INFO][14:18:41] Exception was:
Traceback (most recent call last):

  File "/usr/lib/python3.7/site-packages/coalib/coala_main.py", line 81, in run_coala
    arg_list=arg_list)

  File "/usr/lib/python3.7/site-packages/coalib/settings/ConfigurationGathering.py", line 387, in gather_configuration
    log_printer)

  File "/usr/lib/python3.7/site-packages/coalib/settings/SectionFilling.py", line 31, in fill_settings
    bear_dirs = section.bear_dirs()

  File "/usr/lib/python3.7/site-packages/coalib/settings/Section.py", line 116, in bear_dirs
    for bear_dir in collect_registered_bears_dirs('coalabears')]

  File "/usr/lib/python3.7/site-packages/coalib/collecting/Collectors.py", line 307, in collect_registered_bears_dirs
    registered_package = ep.load()

  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2342, in load
    self.require(*args, **kwargs)

  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2365, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)

  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.VersionConflict: (pylint 2.1.1 (/home/mp/.local/lib/python3.7/site-packages), Requirement.parse('pylint~=1.6'))
```

**Comment by KaustubhDamania** [comment]
Can I work on this issue?

**Comment by Akhelesh** [comment]
Please assign me this issue

**Comment by li-boxuan** [comment]
Thanks for reporting. This issue should belong to `coala-bears` repo. Migrated to https://github.com/coala/coala-bears/issues/2826
