### ISSUE TITLE
coala -A throws exception on EOF signal

### ISSUE THREAD

**Issue by frextrite** [coala/coala#6003]
## Overview Description
Sending EOF signal to `coala -A` results in EOFError

## Steps to Reproduce

1. run coala with `-A` or `--single-action` flag
2. press Ctrl-D(EOF signal)
3. EOFError is dumped to the console

## Actual Results
EOFError is dumped on console with the following traceback
```
Traceback (most recent call last):
  File "/home/amol/anaconda3/envs/coala/bin/coala", line 11, in <module>
    load_entry_point('coala', 'console_scripts', 'coala')()
  File "/home/amol/GitHub/coala/coalib/coala.py", line 121, in main
    return mode_normal(console_printer, None, args, debug=debug)
  File "/home/amol/GitHub/coala/coalib/coala_modes.py", line 29, in mode_normal
    debug=debug)
  File "/home/amol/GitHub/coala/coalib/coala_main.py", line 116, in run_coala
    choice = input(line)
EOFError
```

## Expected Results
A better message like, `Found EOF. Exiting gracefully.` should be shown and the process must exit with status code 0

## Reproducibility
100%

## Additional Information:
difficulty/low
coala/main

**Comment by osadia** [comment]
I would like to work on this issue; Issue#6003 (coala -A throws exception on EOF signal) Could you assign it to me, please. I am supper excited to help! This would be my very first contribution. Thanks!

**Comment by frextrite** [comment]
Please go through coala's [Newcomer's Guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html), join coala's Gitter channel and ping any maintainer to assign you this issue.

**Comment by RJ722** [comment]
Hi @osadia, I am unable to assign you this issue currently because you are not a part of the coala-newcomers team. Please post on Gitter to get an invite.

**Comment by osadia** [comment]
I have posted ‘Hello World’ on Gitter. Would that be enough to get me an invite? Thank you!

**Comment by RJ722** [comment]
@osaida currently, corobo (our chatbot for sending invites, assigning issues, etc.) is down so you might not get an invite immediately, but a maintainer would invite you as soon as they look at your message.

**Comment by osadia** [comment]
@RJ722 Sounds good. Thanks!

**Comment by humpylin** [comment]
Can I please be assigned this?

**Comment by osadia** [comment]
Hi @RJ722, will you be able to assign this issue to me now? Thanks!

**Comment by RJ722** [comment]
Have you accepted the invitation @osadia yet, because I can't find you in the coala/newcomers group?

@humpylin @osadia has already asked for assignment. Please go through https://coala.io/new if you want to find other newcomer issues to work onto.

**Comment by osadia** [comment]
Hi @RJ722, I have never gotten an invite even though I followed the direction in the documentation for the new comers. Is it possible that it’s just taking time?
Thanks!

**Comment by RJ722** [comment]
Yes @osadia. Maintainers must've been busy. Also, messages are easily lost due to a large volume of messages on the general channel. As soon as you get an invitation to the coala/newcomers group, ping here and I'd assign you the issue.

**Comment by osadia** [comment]
Sounds good. Thanks @RJ722!

**Comment by KVGarg** [comment]
Hi @RJ722 Can you please assign me on this issue?

**Comment by RJ722** [comment]
Hello @KVGarg,

@osadia asked first 😅. You can find other issues at https://coala.io/new

**Comment by KVGarg** [comment]
Completed newcomer process, looking forward to contribute more 😇

**Comment by AkshJain99** [comment]
@li-boxuan if no one is working on this issue can i be assigned to this ?

**Comment by abhishalya** [comment]
@RuidongLiu has already created a PR for this, there's no point in creating a new one. You can find issues better than this @AkshJain99 ;)

**Comment by AkshJain99** [comment]
@abhishalya actually that was not assigned to him thats why I asked no problem looking to some other 
:thumbsup:

**Comment by akshatkarani** [comment]
A similar error exists if Ctrl -C is pressed, it dumps KeyboardInterrupt.

**Comment by prateekj117** [comment]
@RJ722 May I work on this issue?

**Comment by KVGarg** [comment]
> @RJ722 May I work on this issue?

A related PR has already been created to solve this issue. Please  look over some another newcomer issue for which no PR has been created yet
