### ISSUE TITLE
Moban non-zero exit code - OSError: File coala-ci-requirements.yaml does not exist

### ISSUE THREAD

**Issue by frextrite** [coala/coala#6114]
Moban job for Travis CI exiting with [non-zero exit code](https://travis-ci.org/coala/coala/jobs/646438375)

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/moban", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/main.py", line 52, in main
    count = handle_moban_file(moban_file, options)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/main.py", line 180, in handle_moban_file
    moban_file_configurations = data_loader.load_data(None, moban_file)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/core/data_loader.py", line 47, in load_data
    child_data = load_data(base_dir, file_name)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/core/data_loader.py", line 32, in load_data
    abs_file_path = search_file(base_dir, file_name)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/moban/core/data_loader.py", line 98, in search_file
    raise IOError(constants.ERROR_DATA_FILE_ABSENT % the_file)
OSError: File coala-ci-requirements.yaml does not exist
The command "moban" exited with 1.
```

**Comment by abhishalya** [comment]
Its fixed now :)
