### ISSUE TITLE
python3: f-string causes "Bear YapfBear failed"

### ISSUE THREAD

**Issue by Pajinek** [coala/coala#6118]
Traceback when new format of f-string is used in Python 3: version `0.12.0.dev99999999999999`

Example:
```
example = "hello"
str = f"{example}"  
```

```Traceback (most recent call last):
  File "/coala/coalib/bears/Bear.py", line 282, in execute
    return [] if result is None else list(result)
  File "/coala-bears/bears/python/YapfBear.py", line 155, in run
    ''.join(file), style_config=fname)[0].splitlines(True)
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 126, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 108, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/lib64/python3.6/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib64/python3.6/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib64/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value='"www.{HOSTNAME}"', context=('', (20, 28))
Executing section all.python.docs...
```

**Comment by SanketDG** [comment]
`f-string`s are available from python version `3.6`, what version are you using?

**Comment by Pajinek** [comment]
My code is written in Python 3.7. And I use for check coala by docker image:

`docker run -ti --rm -v '${CURDIR}:/app:Z' -w /app coala/base coala -an`

**Comment by cathlinlord** [comment]
As part of a computer science course, my team and I are working towards contributing to open source code. If possible, we would like to work on this issue. Thanks!

**Comment by stephensonc** [comment]
@Pajinek, I am a member of the team that @cathlinlord mentioned and have been investigating this issue. It would seem as though the issue stems from the lib2to3 module of python 3.6 not parsing f-strings correctly as documented [here](https://github.com/google/yapf/issues/342). 

It is using the 3.6 version of lib2to3 because the docker base image  on DockerHub is outdated. The dockerfile in the docker-coala-base repository is set to use python 3.6, even though OpenSUSE Tumbleweed no longer has the binary for python 3.6, as seen [here](https://github.com/coala/docker-coala-base/issues/253). 

Our team did discover a temporary workaround to the issue that you are facing, though it is an unsustainable approach. The workaround that we found was to download the lib2to3 module from the [cpython repository](https://github.com/python/cpython/tree/master/Lib/lib2to3) and to manually replace the lib2to3 module in the docker container with the newer version's lib2to3 module.

In order to do this, we opened a container using the coala/base image and had it run an interactive terminal so that we could navigate to and replace the lib2to3 module found in `/usr/lib64/python3.6/` with the updated version. 
The terminal was opened using this command, where `your-folder-here` is the folder you aim to use inside the container: `docker run -it --mount src="$(pwd)",target=/your-folder-here,type=bind coala/base bash`. (This was opened on Ubuntu)

Hopefully this can help you resolve the issue you are having.

**Comment by Fusion-Pie** [comment]
Hey! I will really like to work on this issue. I will try my best to solve this issue if I get assigned to it. Thank you

**Comment by abhishalya** [comment]
@Fusion-Pie No assignment required, feel free to work on this :)
