### ISSUE TITLE
Ma

### ISSUE THREAD

**Issue by abhishalya** [coala/coala#6168]
From [build](https://travis-ci.com/github/coala/coAST/builds/226175353):

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vc8rcv98/coala/setup.py", line 17, in <module>
        from coalib.misc.BuildManPage import BuildManPage
      File "/tmp/pip-build-vc8rcv98/coala/coalib/misc/BuildManPage.py", line 73
        sections = {'see also': (f'Online documentation: {
    SyntaxError: invalid syntax
```

@anshalshukla Can you take a look? Looks like we broke something after the f-string merge.

**Comment by anshalshukla** [comment]
@abhishalya, I think the syntax is fine. The problem is coAST CI is using Python3.5, which does not support f-strings. I am raising an issue on coAST to upgrade its CI configuration to Python 3.6, so I think you can close this issue.

**Comment by Srivastava57Harsh** [comment]
If this issue still open, can I work on it ?
