### ISSUE TITLE
Unable to use CheckstyleBear in .coafile

### ISSUE THREAD

**Issue by csndylim** [coala/coala#6185]
Executing section CheckstyleBear...
[ERROR][07:51:00] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][07:51:00] Exception was:
Traceback (most recent call last):
  File "/coala/coalib/coala_main.py", line 113, in run_coala
    console_printer=console_printer)
  File "/coala/coalib/processes/Processing.py", line 710, in execute_section
    console_printer=console_printer)
  File "/coala/coalib/processes/Processing.py", line 384, in instantiate_processes
    console_printer=console_printer)
  File "/coala/coalib/processes/Processing.py", line 321, in instantiate_bears
    timeout=0.1)]
  File "/coala/coalib/processes/Processing.py", line 315, in <listcomp>
    local_bear_list = [bear
  File "/coala/coalib/processes/Processing.py", line [29](https://gitlab.com/mygitlab/myrepo/-/jobs/4340074561#L29)1, in filter_raising_callables
    yield elem(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/coala_utils/decorators.py", line [34](https://gitlab.com/mygitlab/myrepo/-/jobs/4340074561#L34)3, in decorated
    return function(*args, **kwargs)
  File "/coala/coalib/bears/Bear.py", line 244, in __init__
    self.setup_dependencies()
  File "/coala-bears/bears/java/CheckstyleBear.py", line 58, in setup_dependencies
    'checkstyle-6.19.jar')
  File "/coala/coalib/bears/Bear.py", line 464, in download_cached_file
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: [40](https://gitlab.com/mygitlab/myrepo/-/jobs/4340074561#L40)4 Client Error: Not Found for url: https://sourceforge.net/projects/checkstyle/files/checkstyle/6.19/checkstyle-6.19-all.jar

**Comment by KartikeyBartwal** [comment]
<img width="1263" height="514" alt="Image" src="https://github.com/user-attachments/assets/ec293fa0-9181-412f-9d37-9a43dcce7a6b" />

Here, the following link is being used to download checkstyle-6.19

`https://github.com/checkstyle/checkstyle/releases/download/checkstyle-6.19/checkstyle-6.19-all.jar`

I tried and it is working i.e downloading the jar file.

There are 2 possible reasons for the issue that you are facing:

1) You already have  `checkstyle-6.19 ` cached locally which is corrupted. This is possible due to this:

```
        filename = join(self.data_dir, filename)
        if exists(filename):
            return filename
```
<img width="1071" height="814" alt="Image" src="https://github.com/user-attachments/assets/161cfeb5-0427-47db-93f3-649f1bbebb76" />


2) There is issue with how checkstyle-6.19 jar file is being downloaded. Need to further drill down on that.
